- Creating Extensions using FFI.md
I had to change the function call (I assume the previous name is deprecated)!
> Fix call in FFI tutorial

- Creating Extensions using FFI.md
Was a bit too quick on the ball there, thanks @apaszke
> Added FFI build call

- Deep Learning with PyTorch.ipynb
Add an explanation about `x.grad` values.
> Add math explanation

- Deep Learning with PyTorch.ipynb
I believe this is more straightforward compared to the previous one. A small change but intuitive using basic differentiation.
> More clear and intuitive math explanation

- Deep Learning with PyTorch.ipynb
> Revert "More clear and intuitive math explanation"

- Reinforcement (Q-)Learning with PyTorch.ipynb
fix issue https://github.com/pytorch/tutorials/issues/10
> add missing env.reset() before plt.imshow

- Deep Learning with PyTorch.ipynb
New users may have found the instructions for the Exercise ambiguous and hence frustrating
[Issue #22 ](https://github.com/pytorch/tutorials/issues/22#issuecomment-277442077).
I've made a simple change to the text of the instructions to make it explicit as to what sort of alteration(s) to the layers are permitted.
> Clarified instructions for Exercise at end

- Reinforcement (Q-)Learning with PyTorch.ipynb
#29 Fix: Unwrap CartPole env to access attributes such as x_threshold
> Issue#29 Fix

- Introduction to PyTorch for former Torchies.ipynb
[fixed] confusing example about the effects of "retain_variables" argument
> Update Introduction to PyTorch for former Torchies.ipynb

- Reinforcement (Q-)Learning with PyTorch.ipynb
#36 : @apaszke 
Thanks for the quick edits to master! But I still had some problems, typically after a few iterations and when the replay memory is sampled. I made a few more changes that appear to fix the problems; please review. Thanks.
> Issue 36: fixing q-learning cuda problems

- Creating Extensions using FFI.md
change add to cadd in my_lib.c
corrected a few typos in main.py
> Corrected typos in FFI tutorial

- advanced_source/numpy_extensions_tutorial.py
- beginner_source/blitz/autograd_tutorial.py
- beginner_source/blitz/cifar10_tutorial.py
- beginner_source/blitz/neural_networks_tutorial.py
- beginner_source/blitz/tensor_tutorial.py
- beginner_source/deep_learning_nlp_tutorial.py
- beginner_source/examples_autograd/tf_two_layer_net.py
- beginner_source/examples_autograd/two_layer_net_autograd.py
- beginner_source/examples_autograd/two_layer_net_custom_function.py
- beginner_source/examples_nn/dynamic_net.py
- beginner_source/examples_nn/two_layer_net_module.py
- beginner_source/examples_nn/two_layer_net_nn.py
- beginner_source/examples_nn/two_layer_net_optim.py
- beginner_source/examples_tensor/two_layer_net_numpy.py
- beginner_source/examples_tensor/two_layer_net_tensor.py
- beginner_source/former_torchies/autograd_tutorial.py
- beginner_source/former_torchies/nn_tutorial.py
- beginner_source/former_torchies/parallelism_tutorial.py
- beginner_source/transfer_learning_tutorial.py
- intermediate_source/char_rnn_classification_tutorial.py
- intermediate_source/char_rnn_generation_tutorial.py
- intermediate_source/reinforcement_q_learning.py
- intermediate_source/seq2seq_translation_tutorial.py
> utf8 headers for python files

- beginner_source/transfer_learning_tutorial.py
1. training and evaluate mode fixed. 
2. interactive mode for plotting
> Bugs fixed in Transfer learning tutorial 

- beginner_source/nlp/sequence_models_tutorial.py
> Fix LSTM model in sequence_models_tutorial.py

- intermediate_source/reinforcement_q_learning.py
Fix #66. Thanks @NataliaDiaz for rasing the issue.  Also made plotting interactive, i.e code doesn't stop running if you don't close the plots.
> Patch RL tutorial

- beginner_source/blitz/autograd_tutorial.py
- beginner_source/blitz/cifar10_tutorial.py
- beginner_source/blitz/neural_networks_tutorial.py
- beginner_source/examples_autograd/tf_two_layer_net.py
- beginner_source/examples_autograd/two_layer_net_autograd.py
- beginner_source/examples_autograd/two_layer_net_custom_function.py
- beginner_source/examples_nn/dynamic_net.py
- beginner_source/examples_nn/two_layer_net_module.py
- beginner_source/examples_nn/two_layer_net_nn.py
- beginner_source/examples_nn/two_layer_net_optim.py
- beginner_source/examples_tensor/two_layer_net_numpy.py
- beginner_source/examples_tensor/two_layer_net_tensor.py
- beginner_source/former_torchies/nn_tutorial.py
- beginner_source/former_torchies/parallelism_tutorial.py
- beginner_source/nlp/advanced_tutorial.py
- beginner_source/nlp/deep_learning_tutorial.py
- beginner_source/nlp/pytorch_tutorial.py
- beginner_source/nlp/sequence_models_tutorial.py
- beginner_source/nlp/word_embeddings_tutorial.py
- custom_directives.py
This PR is with respect to Issue #68
> Fix for Indentation error #68

- requirements.txt
Add missing dependencies.
Tested in a clean docker container.
> Add missing dependencies: sphinx, sphinx_rtd_theme, matplotlib.

- beginner_source/former_torchies/tensor_tutorial.py
It's currently unclear what "much more consistent as well"
means -- let's just say what we mean upfront.
> Simplify description of CPU/GPU tensor type consistency.

- intermediate_source/char_rnn_classification_tutorial.py
- intermediate_source/char_rnn_generation_tutorial.py
- intermediate_source/seq2seq_translation_tutorial.py
> unicode strings for 2.7 compatibility

- beginner_source/nlp/word_embeddings_tutorial.py
> minor math equation error

- beginner_source/data_loading_tutorial.py
> fixed typo in beginner_source/data_loading_tutorial.py

- beginner_source/data_loading_tutorial.py
change `landmarks_frame` in the definition of class `FaceLandmarksDataset` to `self.landmarks_frame`
> fix a  small mistake

- intermediate_source/reinforcement_q_learning.py
Expected output of select_action is [torch.LongTensor of size 1x1]
> Fix dim of action in q_learning tutorial

- advanced_source/neural_style_tutorial.py
> Typo in neural style tutorial

- advanced_source/neural_style_tutorial.py
Pretty sure the math part is a typo
> Fixed math typo and grammar errors

- advanced_source/super_resolution_with_caffe2.py
> Elaborate the install instructions more.

- advanced_source/super_resolution_with_caffe2.py
> Add a link to PyTorch onnx documentation.

- advanced_source/super_resolution_with_caffe2.py
> tiny change to super-resolution tutorial

- beginner_source/transfer_learning_tutorial.py
Use more descriptive variable names & lr schedulers
> Improve transfer learning tutorial 

- beginner_source/blitz/neural_networks_tutorial.py
> Add note about input size in blitz

- advanced_source/super_resolution_with_caffe2.py
So it is compatible with latest ONNX.
@ezyang @bddppq
> Update the Super Resolution example

- custom_directives.py
> Fix custom directive 'galleryitem'

- beginner_source/nlp/deep_learning_tutorial.py
Issue: https://github.com/pytorch/pytorch/issues/3441
> Fix a typo

- index.rst
- intermediate_source/README.txt
Intermediate tutorials now will not have any subheadings.
> A few cosmetic changes

- beginner_source/transfer_learning_tutorial.py
I think there are some small typos: dataloders should be dataloaders.
> Change 'dataloders' to 'dataloaders'

- intermediate_source/seq2seq_translation_tutorial.py
Tested with modified code. The tutorial works fine.
> Removed unused references to encoder_output in the attention decoder

- advanced_source/neural_style_tutorial.py
changed "confortable" to "comfortable"
> Fixed a typo

- beginner_source/blitz/cifar10_tutorial.py
this doesn't really deserve a pull request but /shrug
thanks for pytorch!
> fix typo in "where do i go next?"

- beginner_source/data_loading_tutorial.py
Rescale's output_size can be tuple or int
> fix comment to match behavior

- beginner_source/nlp/deep_learning_tutorial.py
- beginner_source/nlp/sequence_models_tutorial.py
- beginner_source/nlp/word_embeddings_tutorial.py
- intermediate_source/char_rnn_classification_tutorial.py
- intermediate_source/char_rnn_generation_tutorial.py
- intermediate_source/seq2seq_translation_tutorial.py
- intermediate_source/spatial_transformer_tutorial.py
These happen because of the 0.3 changes.
> Fix softmax warnings in tutorials

- beginner_source/transfer_learning_tutorial.py
Otherwise best_model_wts changes always to last epoch's state
> Fixed deep copying model.state_dict()

- beginner_source/transfer_learning_tutorial.py
This fixes #179 by simply initializing the criterions with `size_average=False`.
> Fix loss calculation in transfer learning tutorial

- advanced_source/numpy_extensions_tutorial.py
- beginner_source/blitz/neural_networks_tutorial.py
- beginner_source/blitz/tensor_tutorial.py
- beginner_source/data_loading_tutorial.py
- beginner_source/examples_autograd/two_layer_net_custom_function.py
- beginner_source/examples_nn/two_layer_net_optim.py
- beginner_source/nlp/pytorch_tutorial.py
- intermediate_source/char_rnn_classification_tutorial.py
1. Add explanation for torch.view: Fixes #113 
2. Add explanation of optim.zero_grad: Fixes #156 
3. Use pandas .iloc instead of deprecated .ix: Fixes #186 
4. Fix link in char rnn tutorial: Fixes #196 
5. fix a bug in nlp tutorial: Fixes #190 
6. Update with new Function API: Fixes #170
> Multiple small fixes 

- beginner_source/blitz/tensor_tutorial.py
I started reading through the docs and had some tiny suggestions if useful.
> Some suggestions regarding typos and style in the Blitz document

- beginner_source/transfer_learning_tutorial.py
> Set transfer learning model in eval mode in visualize_model function

- beginner_source/transfer_learning_tutorial.py
Fix a couple of typos as well as calls to deprecated PyTorch methods.
> Minor fixes to Transfer Learning

- beginner_source/nlp/deep_learning_tutorial.py
Makes it consistent with later in the paragraph
> Fix typo for BoW

- advanced_source/neural_style_tutorial.py
> Update Neural Style Transfer to print weighted loss

- advanced_source/cpp_extension.rst
> Some corrections to the C++ extensions tutorial

- beginner_source/blitz/autograd_tutorial.py
Typo fixing and formatting change in autograd tutorial
> Typo fixing and formatting change

- beginner_source/examples_nn/two_layer_net_nn.py
removed `and` and add `its` to be clear.
> fixed a typo at two_layer_net_nn.py

- advanced_source/cpp_extension.rst
@soumith 
Fixes https://github.com/pytorch/extension-cpp/issues/8
> nn.Function -> autograd.Function

- beginner_source/blitz/autograd_tutorial.py
- beginner_source/blitz/tensor_tutorial.py
> Grammar fixes in Blitz tutorials

- beginner_source/blitz/data_parallel_tutorial.py
.cuda() should be used in v0.3.1 instead of .gpu()
> fix .gpu() bug

- requirements.txt
> Fix incorrectly formatted pip requirements file

- beginner_source/nlp/pytorch_tutorial.py
Identical to https://github.com/pytorch/tutorials/pull/242
> Typo fix and reformatting

- advanced_source/cpp_extension.rst
`AT_ASSERT(cond, ...)` -> `AT_ASSERTM(cond, ...)`
https://github.com/pytorch/pytorch/blob/v0.4.1/aten/src/ATen/Error.h#L123
> Fix typos and update to 0.4.1

- beginner_source/chatbot_tutorial.py
Removing this step prevents the tutorial builds halting.
> Comment Out Interactive Step

- beginner_source/audio_classifier_tutorial.py
Very minor changes that shouldn't cause any problems.
> decrease train time and small typo fix

- advanced_source/cpp_extension.rst
> Clarify sentence in C++ extensions tutorial

- beginner_source/chatbot_tutorial.py
- beginner_source/saving_loading_models.py
@ericnakagawa @JoelMarcey 
Should be safe to merge this, just minor changes to markdown.
> Fixed headings in saving_loading_models tutorial and wording/grammatical nits in chatbot tutorial

- advanced_source/cpp_extension.rst
> Create FAQ for C++ extensions

- advanced_source/cpp_export.rst
> Some nits in TorchScript export tutorial + note about cuda

- advanced_source/README.txt
- advanced_source/cpp_export.rst
- advanced_source/cpp_extension.rst
- advanced_source/neural_style_tutorial.py
- advanced_source/super_resolution_with_caffe2.py
- beginner_source/README.txt
- beginner_source/blitz/README.txt
- beginner_source/blitz/autograd_tutorial.py
- beginner_source/blitz/cifar10_tutorial.py
- beginner_source/blitz/data_parallel_tutorial.py
- beginner_source/blitz/neural_networks_tutorial.py
- beginner_source/blitz/tensor_tutorial.py
- beginner_source/chatbot_tutorial.py
- beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
- beginner_source/former_torchies/README.txt
- beginner_source/former_torchies/parallelism_tutorial.py
- beginner_source/hybrid_frontend/README.txt
- beginner_source/hybrid_frontend/learning_hybrid_frontend_through_example_tutorial.py
- beginner_source/nlp/README.txt
- beginner_source/nlp/pytorch_tutorial.py
- beginner_source/transfer_learning_tutorial.py
- index.rst
- intermediate_source/README.txt
- intermediate_source/char_rnn_classification_tutorial.py
- intermediate_source/char_rnn_generation_tutorial.py
- intermediate_source/dist_tuto.rst
- intermediate_source/seq2seq_translation_tutorial.py
Ref https://github.com/pytorch/pytorch/issues/13951
> http to https for pytorch.org in the tutorial documentation

- intermediate_source/reinforcement_q_learning.py
Changes "rescare" to "rescale"
> Fix typo in reinforcement learning tutorial

- advanced_source/torch_script_custom_ops.rst
- index.rst
> Adding tutorial for TorchScript custom ops

- advanced_source/torch_script_custom_ops.rst
Consolidating links now that the tutorial and repo are out.
@soumith
> Fix link to tutorial repo

- advanced_source/cpp_extension.rst
> Fix FAQ link

- beginner_source/audio_classifier_tutorial.py
Please don't merge until we see if this fixes build issue. Thanks.
> Reducing epochs in audio_classifier to fix build issue.

- .gitmodules
Let's see if this allows Netlify to build without breaking our build
> Add Pytorch Sphinx theme as proper submodule

- advanced_source/cpp_extension.rst
cc: @goldsborough I dont think your code ever worked
> fix c++ extensions tutorial

- .gitignore
Add temporary download data dir `_data/` to `.gitignore`
Sorry for missing in PR #390 
Please review this PR.
> Ignore temporary download data dir

- beginner_source/nn_tutorial.py
Reported in https://github.com/pytorch/tutorials/issues/410.
> Updated gzip command to fix issue on Ubuntu 16.

- intermediate_source/reinforcement_q_learning.py
The current explanation is a little confusing and had me read the paragraph twice to understand. _Very_ small change, but should improve readability.
> Update reinforcement_q_learning: small grammer fix

- beginner_source/nn_tutorial.py
Removing the duplicated word ”about” in the explanation of using cloud GPUs and their cost.
> Update nn_tutorial.py: removing duplicated word

- .circleci/config.yml
Test plan: make sure CircleCI passes.
> Use Docker image version 291

- .circleci/config.yml
- .jenkins/build.sh
According to https://github.com/pytorch/pytorch/issues/16935, using nightly build should fix the error.
> Fix CUDNN error in spatial_transformer_tutorial.py

- intermediate_source/reinforcement_q_learning.py
This commit removes hard-coded entries for the output action space
and gets the value directly from the gym environment.
Signed-off-by: Elvis Dowson <elvis.dowson@gmail.com>
> reinforcement_q_learning: Remove hard-coded entries for action space.

- beginner_source/dcgan_faces_tutorial.py
Correction done from log(1-D(G(x))) to log(1-D(G(x))).
Please review
> It should be log(1-D(G(z)))

- beginner_source/nn_tutorial.py
Link to the bottom of the page no longer necessary.
> Update nn_tutorial to reflect UI change

- beginner_source/dcgan_faces_tutorial.py
@inkawhich, it strike to me that the original link of dataset celeA is broken. So this PR is to fix it.
> fix broken link

- advanced_source/cpp_extension.rst
Along with more up to date function calls,
a tutorial for packed tensor accessors is proposed.
See the corresponding PR in cpp-extension [here](https://github.com/pytorch/extension-cpp/pull/33)
> Upgrade CPP extension tutorial

- index.rst
- intermediate_source/ddp_tutorial.rst
This is converted from #478 to avoid an error when using sphinx + multiprocessing + ipython, where a top-level function cannot be passed to a sub-process.
> Adding DDP tutorial in rst format

- beginner_source/data_loading_tutorial.py
Border lines of the grids are not considered; The coordinates of the landmarks should be shifted accordingly.
> Fixed a bug in data_loading_tutorial

- beginner_source/blitz/cifar10_tutorial.py
1. Fix: Moving input "data" to device. 
2. This in-turn benefits from describing what "data" list is composed of.
> moving input data to device

- intermediate_source/model_parallel_tutorial.py
> Highlight that Model Parallel performance numbers are environment dependent

- beginner_source/data_loading_tutorial.py
as_matrix is deprecated. So it will be misleading for beginners like me
> as_matrix deprecated in pandas

- .jenkins/build.sh
- requirements.txt
Pinning sphinx gallery. Step one.
Please don't merge.
> Build Repair Work: build-fix branch

- .jenkins/build.sh
> [WIP] Torchtext Update for build.sh

- index.rst
Added torchscript intro to left nav.
> Update index.rst - Adds torchscript to left nav

- beginner_source/Intro_to_TorchScript_tutorial.py
- index.rst
Adds tutorial with naming to generate output in html (_tutorials.py). Will add a redirect to the site from the old page. https://pytorch.org/tutorials/beginner/Intro_to_TorchScript.html
> [WIP] Torchscript intro update

- intermediate_source/flask_rest_api_tutorial.py
As discussed in the previous PR https://github.com/pytorch/tutorials/pull/611
> Add serving batching: point to service-streamer tutorial

- intermediate_source/tensorboard_tutorial.rst
Several image links pointed to the wrong images.
> Fixed static image links

- beginner_source/examples_autograd/tf_two_layer_net.py
- beginner_source/examples_autograd/two_layer_net_autograd.py
- beginner_source/examples_autograd/two_layer_net_custom_function.py
- beginner_source/examples_nn/dynamic_net.py
- beginner_source/examples_nn/two_layer_net_module.py
- beginner_source/examples_nn/two_layer_net_nn.py
- beginner_source/examples_nn/two_layer_net_optim.py
- beginner_source/examples_tensor/two_layer_net_tensor.py
- beginner_source/transfer_learning_tutorial.py
* Change printing in examples tutorials to only print every 100 iterations, instead of every 500, to not create a cell with a ton of output in people's notebooks. 
* Move `scheduler.step()` after `optimizer.step()` in accordance with PyTorch 1.1 best practices.
> Misc changes

- intermediate_source/tensorboard_tutorial.rst
Fixed code formatting issue in tensorboard tutorial.
> Fix formatting issues in tensorboard tutorial

- advanced_source/cpp_frontend.rst
Corrections per this PR: https://github.com/pytorch/pytorch/issues/25644
> Correct errors in the TorchModule code to match the sequential version

- beginner_source/chatbot_tutorial.py
change ByteTensor to BoolTensor
> fix the warning when training

- advanced_source/cpp_export.rst
- advanced_source/super_resolution_with_onnxruntime.py
- beginner_source/Intro_to_TorchScript_tutorial.py
- beginner_source/aws_distributed_training_tutorial.py
- intermediate_source/ddp_tutorial.rst
- intermediate_source/dist_tuto.rst
- intermediate_source/flask_rest_api_tutorial.py
- intermediate_source/model_parallel_tutorial.py
Remove numbers from tutorials names in new sections, per @jspisak.
> Remove numbers from tutorial names

- intermediate_source/dist_tuto.rst
> Updates to distributed tutorial

- advanced_source/cpp_frontend.rst
Remove erronenous conv5 from example code
> Remove erroneous conv5

- .circleci/config.yml
> Update CUDA driver

- index.rst
Re-add the model parallel tutorial after updating the CUDA driver (#688).
@soumith FYI.
> Re-add model parallel tutorial

- advanced_source/super_resolution_with_onnxruntime.py
Small typing error fix, from wether to whether
> Fix tutorial comment typing error

- beginner_source/transformer_tutorial.py
fix for #682 
Signed-off-by: David Pollack <david@i2x.ai>
> Fix CrossEntropyLoss in transformer tutorial

- Makefile
- advanced_source/static_quantization_tutorial.py
@raghuramank100 adding language making it clear for readers how to download the files associated with this tutorial.
> Add paths for downloaded files to static quantization tutorial

- .gitignore
- Makefile
- conf.py
Submitting changes from PR #758 from a branch rather than from a fork to avoid circleci build issues.
> Adding Zafar's changes from PR #758 to run flags + gitignore additions

- intermediate_source/reinforcement_q_learning.py
- torch.uint8 is now deprecated, moving to torch.bool
> reinforcement_q_learning: resolving torch.uint8 is now deprecated warning

- beginner_source/transfer_learning_tutorial.py
Correct link to Quantized Transfer Learning for Computer Vision Tutorial
> Correct link

- beginner_source/deep_learning_60min_blitz.rst
- index.rst
Updates to prune older tutorials and restructure existing ones
> Tutorials Refresh - Update TOC

- beginner_source/blitz/tensor_tutorial.py
This update is in reference to the PyTorch Tutorial update strategy.
- Addressed issues #774 #775 #776 
- Made updates to the learning narrative of the tutorial
> 60-Min Blitz: What is PyTorch

- beginner_source/blitz/autograd_tutorial.py
This update is in reference to the PyTorch Tutorial update strategy.
- Addressed issues #777 , #778 , #779 , #780 
- Gave more context to gradient descent, back propagation, automatic differentiation
- Added new code blog to explain gradient functions
> 60-Min Blitz- Autograd: Automatic Differentiation

- conf.py
- custom_directives.py
- index.rst
- Updates conf.py and custom_directives.py with build changes needed for new tutorials cards to render (https://github.com/pytorch/pytorch_sphinx_theme/pull/69)
- Pull in new RPC tutorial from master index.rst
> Add Build files for new tutorials cards and merge in updates to master index.rst

- .circleci/config.yml
Similar to https://github.com/pytorch/pytorch/pull/34241
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> Bump NVIDIA driver to 440.59, for CUDA 10.2 compat

- .jenkins/build.sh
- README.md
- beginner_source/audio_preprocessing_tutorial.py
Still testing build for 1.5. Restarting from master to recheck the errors.
> Test branch for 1.5 

- .jenkins/build.sh
- README.md
- beginner_source/audio_preprocessing_tutorial.py
> Brianjo patch test

- intermediate_source/dist_tuto.rst
As discussed in https://github.com/pytorch/pytorch/issues/31572, the allreduce implementation is not correct (confirmed by mutiple persons). This PR is proposed to fix the bug.
> Fix allreduce implmentation in tutorial

- .jenkins/build.sh
- requirements.txt
Build testing. Don't merge yet.
> Brianjo hash fix

- .jenkins/build.sh
Sets --pre in pip for nightly build.
> Rebuild Nightly

- .circleci/config.yml
Since it takes 3+ hours to finish and has been timing out for the last two weeks days
> Run win_test_worker manually

- .circleci/config.yml
See https://github.com/pytorch/tutorials/issues/1141
> Disable `pytorch_windows_builder_worker` config

- _templates/layout.html
The PR adds event tracking to the call-to-action links at the top of each tutorial. Preview: https://5f85b3cc4faec823557eb00a--shiftlab-pytorch-tutorials.netlify.app/
> Update event tracking

- beginner_source/nn_tutorial.py
Will revert when deeplearning.net comes back online.
> Adds gh link to mnist dataset

- beginner_source/nlp/sequence_models_tutorial.py
Changes to "Sequence Models and Long-Short Term Memory Networks" beginner tutorial:
- Added code comments for one of the code snippets
- Referred to "Word Embeddings" tutorial
Rationale, some people:
- May not be familiar with embeddings
- May find the nested loops/conditional statements hard to follow
- May be unfamiliar with grammar terminology (such as realising why `DET` maps to the word "the")
> Added comments to LSTM Sequence Models tutorial

- beginner_source/profiler.py
- recipes_source/recipes/profiler_recipe.py
Summary:
Mention new profiler API.
Test Plan:
make html-noplot
> Update profiler docs

- _templates/layout.html
This PR updates analytics to capture tutorial ratings. The design changes and a preview of the update can be viewed in this PR: https://github.com/pytorch/pytorch_sphinx_theme/pull/95.
> Update analytics to capture star ratings

- _templates/layout.html
- index.rst
Fix to collapse video section.
> Brianjo expand fix

- .jenkins/build.sh
Disable build of tutorial as the mnist download fails right now.
> fgsm_tutorial temp disable - build fix update build.sh

- .jenkins/build.sh
Needed to temporarily disable intermediate_source/spatial_transformer_tutorial.py for a download issue.
> Temp disable spatial_transformer_tutorial - update build.sh

- index.rst
> Adds vt_tutorial to TOC.

- beginner_source/data_loading_tutorial.py
Amended a typo in part of the description.
> Minor typo

- index.rst
Test for adding a temporary survey option to the site.
> Adds temporary reader survey to site. 

- intermediate_source/pipeline_tutorial.py
Summary: As described in
https://github.com/pytorch/pytorch/issues/55036, certain modules were
not handling batch size correctly.
> Fix bugs in pipeline tutorial with respect to batch size.

- index.rst
Adds links to the static quantization tutorial to the index page.
> Add static quant to index

- beginner_source/deeplabv3_on_ios.rst
- recipes_source/android_native_app_with_custom_op.rst
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #1494 Update tutorials for custom inplace & view ops.
* **#1493 Replace AutoNonVariableTypeMode with InferenceMode in user facing tutorial.**
> Replace AutoNonVariableTypeMode with InferenceMode in user facing tutorial.

- beginner_source/text_sentiment_ngrams_tutorial.py
While going through the tutorial, I found some minor typos, so I fixed them.
Thanks
> Fixed Typos

- beginner_source/basics/data_tutorial.py
Remove unused `Lambda` module from import
> remove unused import

- beginner_source/text_sentiment_ngrams_tutorial.py
> Typo fix in text sentiment tutorial

- .circleci/config.yml
Reverts pytorch/tutorials#1184
This PR was old and I think it's causing trouble with the builds. Trying a revert to see if the build succeeds.
> Revert "Added cache for incremental build."

- beginner_source/audio_preprocessing_tutorial.py
- beginner_source/dcgan_faces_tutorial.py
part of torchaudio 0.9 release [checklist](https://github.com/pytorch/audio/issues/1527)
- update HTK support and metadata printing
- add resampling tutorial
> Update audio manipulation tutorial 

- beginner_source/transformer_tutorial.py
> updated transformer tutorial

- beginner_source/translation_transformer.py
> updated translation tutorial

- intermediate_source/torchvision_tutorial.rst
Fixes issue https://github.com/pytorch/tutorials/issues/759
> Updated dataset in torchvision tutorial

- beginner_source/basics/transforms_tutorial.py
fixes issue https://github.com/pytorch/tutorials/issues/1548
> added missing "import torch" to LTB Transforms

- recipes_source/recipes/dynamic_quantization.py
The mentioned issue was closed 1.5 years ago, so it shouldn't be relevant any more.
> Remove note on very old version

- recipes_source/recipes/loading_data_recipe.py
replaced :: with ! and comments; replaced ^^^^ with ____; removed :: and commented code and inserted code directly.
> style issue fix for loading_data_recipe.py showing in colab

- beginner_source/basics/data_tutorial.py
Change all instances of the word "Dataloader" to "DataLoader" in data_tutorial.py
> Fix capitalization for the word "DataLoader"

- beginner_source/transformer_tutorial.py
* added typing annotations
* improved text documentation
* added some function docstrings
* rewrote confusing code
* fix bug: now actually uses best model on test set (by saving the best model via `copy.deepcopy()`)
> Transformer Tutorial: improve code understandability and documentation

- intermediate_source/memory_format_tutorial.py
> Fix text and image mismatch

- advanced_source/rpc_ddp_tutorial/main.py
- intermediate_source/ddp_tutorial.rst
Context: #1619
1619 was merged into a wrong branch (non-master)
Example code fix: pytorch/examples#924
> Real: redo rank --> trainer_rank doc fix

- beginner_source/text_sentiment_ngrams_tutorial.py
predited_label -> predicted_label
> Fix spelling error to improve legibility

- recipes_source/recipes/defining_a_neural_network.py
> fix typo in defining_a_neural_network.py

- intermediate_source/custom_function_conv_bn_tutorial.py
> Update fused conv bn tutorial

- advanced_source/neural_style_tutorial.py
Hopefully this should be enough to prevent worker 9 from running out of GPU memory.
> Cleanup of the neural style transfer to reduce memory usage

- advanced_source/dispatcher.rst
- @albanD has mentioned that maybe `Fallback` isn't the best name since its not a real "fallback". It is probably best not to overload the the term, and instead have something like `REGISTER_AUTOGRAD_NOT_IMPLEMENTED_KERNEL`.
- The exact API is not 100% determined, but starting to write this doc can help us think about what it will look like.
- Any other places where this new macro can be linked?
> Add autograd not implemented to dispatcher tutorial

- beginner_source/nlp/word_embeddings_tutorial.py
Following #1666, I think `CONTEXT_SIZE` should be used to preprocess data in the code examples. Also, I think it would be a good idea to lowercase/remove punctuation in the sample texts.
> Improvements to word embeddings tutorial.

- beginner_source/dcgan_faces_tutorial.py
> fix typo in weight initialization comment

- recipes_source/recipes/loading_data_recipe.py
Fixes https://github.com/pytorch/pytorch.github.io/issues/835
> Fix `loading_data_recipe` links

- beginner_source/blitz/tensor_tutorial.py
Two changes:
* consistent spaces after a comma in different places
* printing result of the operation of moving tensor to GPU
> Misc updates in tensor_tutorial

- intermediate_source/forced_alignment_with_torchaudio_tutorial.py
Porting the update from https://pytorch.org/audio/main/tutorials/forced_alignment_tutorial.html
1. Update and fix rendering
2. Dislay audio items
> Update forced alignment tutorial

- recipes_source/recipes/Captum_Recipe.py
Should fix the formatting in the first section of this tutorial to render as a unordered list I think.
> Update Captum_Recipe.py: Fix formatting

- beginner_source/transfer_learning_tutorial.py
> Changed == to = as in the code

- beginner_source/examples_nn/dynamic_net.py
The further code (and the comment closer to it) uses a random int number from [4, 5], not [3, 5]
> Fix the number in the example

- intermediate_source/memory_format_tutorial.py
Fixes https://github.com/pytorch/pytorch/issues/71208.
> Fix typo operatos -> operators

- intermediate_source/realtime_rpi.rst
This adds model benchmarks from https://docs.google.com/document/d/1pCrvfoIdBbvZDwZhIN2rNT6IFFXebCfkUPRclebTrE4/edit#heading=h.gcsiqautb2mx to give users a rough idea of what models / performance they can run on their devices.
It also addresses feedback + cleanup from the previous PR.
https://github.com/pytorch/tutorials/pull/1821
Test Plan:
> intermediate/realtime_rpi: updated with benchmarks + feedback

- .circleci/config.yml
s/gpu.medium/nvidia.gpu.medium/
> [CircleCI] Change runner type

- .jenkins/build.sh
Reverts pytorch/tutorials#1833
> Revert "Enables intermediate_source/model_parallel_tutorial.py for testing"

- .jenkins/build.sh
Reverts pytorch/tutorials#1832
Build config between PR and trunk are unified now
> Revert "Update build.sh"

- recipes_source/recipes/saving_and_loading_a_general_checkpoint.py
modify spelling error
line 45 , 63 spelling error
intial (x)-> initial(o)
'i' is omitted
> modify spelling

- .circleci/config.yml
- .jenkins/build.sh
- requirements.txt
This also updates default python version to 3.7
> Update default python to 3.7

- intermediate_source/FSDP_tutorial.rst
PR fixes the link to 1T model blog post.
> fix the blog link

- intermediate_source/FSDP_tutorial.rst
PR fixes the not rendered code snippets
> Fsdp code fixes

- beginner_source/transfer_learning_tutorial.py
In almost all places the f-string is more readable than the format - especially for beginners.
> switch format to f-string

- .circleci/config.yml
Prep change for Ubuntu-20.04 update
> Use CircleCI docker+nvidia capable images

- LICENSE
- conf.py
Noticed that after reading https://github.com/pytorch/tutorials/issues/941
> Update Copyright notice to 2022

- .circleci/config.yml
- .circleci/config.yml.in
- .jenkins/get_docker_tag.py
> use docker hub latest image

- advanced_source/sharding.rst
- index.rst
- Added the TorchRec sharding tutorial to index.rst
- FIx minor markup issues
- Gave the tutorial a name
> Add the sharding tutorial to index.rst

- intermediate_source/reinforcement_q_learning.py
Fix broken link to "Gym website" in the Reinforcement Learning (DQN) Tutorial
> Fix broken link in Reinforcement Learning Tutorial

- recipes_source/recipes/tuning_guide.py
oneDNN Graph support for Float32 inference would be an experimental/prototype feature in PyTorch 1.12.
Thank you!
> Add info on oneDNN Graph to the tuning guide

- .circleci/config.yml
- .circleci/config.yml.in
As system has been migrated to Focal few month back
> [CI] Delete trusty PGP key install

- .jenkins/build.sh
> Re-enable tensorboard_profiler_tutorial.py

- intermediate_source/bettertransformer_tutorial.rst
> Update google colab link

- beginner_source/audio_data_augmentation_tutorial.py
Addresses: #1930
Ref: https://github.com/pytorch/audio/pull/2595
> Fix audio data augmentation tutorial

- intermediate_source/torchvision_tutorial.rst
> Update TorchVision tutorial to use the latest reference transforms

- Makefile
- beginner_source/chatbot_tutorial.py
- beginner_source/colab.rst
Location and format of cornell movie-dialogs corpus have changed a bit (format changed from 2 text files-movie_lines and movie_conversations to a single utterances json file) and so the existing tutorial doesn't load and process the new data format properly. Updated the code and comments to work on the updated data format.
Working of updated code
```
(venv38) ?130 priyaramani@priyaramani-mbp chatbot % python chatbot.py
b'{"id": "L1045", "conversation_id": "L1044", "text": "They do not!", "speaker": "u0", "meta": {"movie_id": "m0", "parsed": [{"rt": 1, "toks": [{"tok": "They", "tag": "PRP", "dep": "nsubj", "up": 1, "dn": []}, {"tok": "do", "tag": "VBP", "dep": "ROOT", "dn": [0, 2, 3]}, {"tok": "not", "tag": "RB", "dep": "neg", "up": 1, "dn": []}, {"tok": "!", "tag": ".", "dep": "punct", …
```
> Fix data preprocessing for chatbot tutorial

- beginner_source/Intro_to_TorchScript_tutorial.py
Grammatically updated the tutorial according to the issue raised.
> Grammatically updated the tutorial

- .jenkins/build.sh
- requirements.txt
Do not install older sphinx, use one from requirements.txt
Move pillow version pinning from build.sh to requirements.txt
Do not delete `src` folder
> Cleanup build.sh

- .jenkins/get_files_to_run.py
Should be a noop but helps with developing on-demand dependencies for
tutorials
> Add argparse to get_files_to_run

- requirements.txt
> Add functorch to requirements

- beginner_source/nn_tutorial.py
> Add a link to mnist_sample notebook

- _static/doctools.js
By running
```
curl -O https://raw.githubusercontent.com/sphinx-doc/sphinx/v5.1.1/sphinx/themes/basic/static/doctools.js
```
Fixes https://github.com/pytorch/tutorials/issues/2015
> Update doctools.js to one from sphinx-5.1.1

- requirements.txt
Probably it will fix the current outage
> Pin ray version to 1.13.0

- conf.py
- requirements.txt
And disable code generation for 2 offending tests: hyperparameter_tuning_tutorial and flask_rest_api_tutorial (neither of them actually need anything from coderuns)
> Update sphinx-gallery version to 0.11.1

- beginner_source/examples_nn/polynomial_module.py
> Add missing backslash in math formula

- intermediate_source/FSDP_tutorial.rst
> Typo fix on FSDP_tutorial.rst

- prototype_source/nestedtensor.py
The api for to_padded_tensor has changed. Updates made to the tutorial to reflect this.
> Update nestedtensor to_padded calls

- .jenkins/validate_tutorials_built.py
- requirements.txt
All it needed is adding missing `deep_phonemizer` package to requirements.txt
> Build TextToSpeech tutorial

- intermediate_source/reinforcement_q_learning.py
Update the DQN tutorial to match the last version of gym
> update rl tutorial to last gym version

- prototype_source/prototype_index.rst
Add tags to the maskedtensor tutorials so they appear when filtering by tag
> Add tags to the maskedtensor tutorials

- .jenkins/validate_tutorials_built.py
- prototype_source/fx_numeric_suite_tutorial.py
> [cheery-pick]update NS for FX tutorial for PyTorch v1.13 (#2089)

- prototype_source/README.md
> Fix minor typo

- .circleci/config.yml
- .circleci/config.yml.in
- .circleci/regenerate.py
- .jenkins/build.sh
Trigger turnk CI on either master or main
> Prep for master->main rename

- intermediate_source/reinforcement_q_learning.py
Original version sounded confusing
> Fix grammar in reinforcement learning tutorial

- beginner_source/basics/quickstart_tutorial.py
cc @malfet @albanD @kulinseth @razarmehr
> Add support of mps for Mac M1 CPUs

- index.rst
Seems like this broke rendering for Ray Tune tutorial
> Fix a small indent error

- prototype_source/fx_graph_mode_ptq_static.rst
fixes the missing instantiation for QConfigMapping
> fix missing QConfigMapping instantiation.

- index.rst
Let's remove the survey link; we've collected enough responses for this iteration of the survey.
cc @svekars
> Remove survey link

- prototype_source/fx_graph_mode_quant_guide.rst
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #2200
> Fix formatting errors in fx graph mode quantization user guide

- beginner_source/audio_datasets_tutorial.rst
The correct target URL is https://pytorch.org/audio/stable/tutorials/audio_datasets_tutorial.html
> Fix infinite redirection in audio dataset tutorial 

- intermediate_source/FSDP_tutorial.rst
cc @mrshenli @osalpekar @H-Huang @kwen2501
> Typo in tutorial, dist_barrier should be dist.barrier

- beginner_source/blitz/autograd_tutorial.py
> modified some text for clarity

- beginner_source/dcgan_faces_tutorial.py
> Fix typo in DCGAN Tutorial

- .circleci/config.yml
upgrade docker image after https://github.com/pytorch/pytorch/pull/102380/files
> Upgrade docker image

- beginner_source/finetuning_torchvision_models_tutorial.rst
Fixes #2097
cc @svekars @carljparker @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael
> Redirect finetuning_torchvision_models_tutorial to torchvision_tutorial

- beginner_source/transfer_learning_tutorial.py
> Replace usage of copy.deepcopy()

- beginner_source/transformer_tutorial.py
> Revert "Update transformer_tutorial.py | Resolving issue #1778"

- .github/workflows/build-tutorials.yml
Add step to upload docs preview in manager
preview at: https://docs-preview.pytorch.org/pytorch/tutorials/2426/index.html
> Upload docs preview

- advanced_source/cpp_frontend.rst
- advanced_source/neural_style_tutorial.py
- beginner_source/chatbot_tutorial.py
- beginner_source/data_loading_tutorial.py
- beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
- beginner_source/fgsm_tutorial.py
- beginner_source/transfer_learning_tutorial.py
- intermediate_source/char_rnn_classification_tutorial.py
- intermediate_source/char_rnn_generation_tutorial.py
- intermediate_source/dynamic_quantization_bert_tutorial.rst
- intermediate_source/seq2seq_translation_tutorial.py
- intermediate_source/spatial_transformer_tutorial.py
- prototype_source/graph_mode_dynamic_bert_tutorial.rst
- prototype_source/numeric_suite_tutorial.py
As Python-2.7 is long past EOL, and all tutorials are living in the future :)
> [BE] Delete `from __future__ import`

- en-wordlist.txt
Update wordlist to pass spellcheck in #2430
> Add new words to wordlist

- prototype_source/quantization_in_pytorch_2_0_export_tutorial.rst
Remove WIP in the title of quantization 2.0 tutorial
> Remove WIP in the title of quantization 2.0 tutorial

- intermediate_source/parametrizations.py
torch.symeig was removed https://github.com/pytorch/pytorch/pull/70988
> Update removed torch.symeig in parametrizations.py

- _templates/layout.html
- conf.py
Re: https://github.com/pytorch/pytorch.github.io/issues/1397
As discussed and proposed, we will update GTAG in conf.py rather than in layout.html. This PR makes sure we have same solution across all repos.
> Update GTAG in conf.py instead of layout.html

- en-wordlist.txt
- intermediate_source/neural_tangent_kernels.py
Allow it to work on CPU
Disable TensorFloat on Ampere+ GPU to meet accuracy expectations
> Improve  Neural Tangent Kernels tutorial

- .github/workflows/build-tutorials.yml
- .jenkins/metadata.json
Changed the number of workers to 15 in attempt to speed up the build.
> Increase the number of workers

- intermediate_source/reinforcement_ppo.py
Adds a missing quote in the PPO tutorial
> Missing quote in PPO

- .jenkins/metadata.json
- conf.py
These machine names need to be changed at some point...
Also 
* run garbage collector
* set numpy random seed
> data_parallel_tutorial to run on multigpu

- intermediate_source/torch_compile_tutorial.py
add `torch.no_grad` call to `evaluate`
> Fix torch_compile_tutorial.py

- prototype_source/fx_graph_mode_ptq_static.rst
- prototype_source/prototype_index.rst
- prototype_source/pt2e_quant_ptq_static.rst
- prototype_source/pt2e_quantizer.rst
Summary:
also renames the current pt2e tutorial
Test Plan:
.
Reviewers:
Subscribers:
Tasks:
Tags:
> [quant][pt2e] Add documentation for pt2 export static quant

- intermediate_source/char_rnn_generation_tutorial.py
Fixes #2498 
Fixed broken link
> Fixes #2498

- intermediate_source/torchvision_tutorial.rst
Forgot to update image_id in rst but using correct type in complete code: https://github.com/pytorch/tutorials/blob/6b31dd0da52178c21170217680370d4430bd1b54/_static/tv-training-code.py#L52
> Fixed issue in torchvision_tutorial.rst

- prototype_source/pt2e_quant_ptq_static.rst
Summary:
.
Test Plan:
visual inspection of generated docs
Reviewers:
Subscribers:
Tasks:
Tags:
> [quant][2.1] fix formatting for the tutorial

- Makefile
As `-N` and `-O` options are mutually exclusive
> Fix `lenet_mnist` download

- beginner_source/basics/saveloadrun_tutorial.py
> Link to nn.module checkpoint loading tutorial in save and load the model recipe

- prototype_source/prototype_index.rst
The typo causes menu issues, reported by a user.
Fixes https://github.com/pytorch/pytorch/issues/111643
> Fix "Model Optimziation" typo

- intermediate_source/reinforcement_ppo.py
Fixes #2620
Fixes the deprecation warning by updating the CUDA check
> Replace deprecated CUDA check

- beginner_source/blitz/autograd_tutorial.py
Fixes #1024
This PR adds an explanation video to the [A Gentle Introduction to `torch.autograd`](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) page.
> Add explanation video to `torch.autograd` tutorial

- intermediate_source/pruning_tutorial.py
Fixes #2311 
changed kernel 5x5 and fixed the corresponding comment in the line above. 
cc @albanD @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
> change kernel size to 5x5

- beginner_source/onnx/export_simple_model_to_onnx_tutorial.py
- beginner_source/onnx/onnx_registry_tutorial.py
Follows https://github.com/pytorch/pytorch/pull/112263
cc @BowenBao
> Rename torch.onnx.ExportOutput to torch.onnx.ONNXProgram

- advanced_source/static_quantization_tutorial.rst
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #2703
Summary: users reported seeing a warning when running a tutorial, add a
comment calling this out as expected. related to https://github.com/pytorch/pytorch/issues/40278
Test Plan: n/a
Reviewers:
Subscribers:
Tasks:
Tags:
> adding warning to quantization tutorial

- .pyspelling.yml
- advanced_source/usb_semisup_learn.py
- en-wordlist.txt
Fix spellcheck that was broken by #2676
> Fix spellcheck

- _templates/layout.html
> Remove 2023 survey

- intermediate_source/reinforcement_q_learning.py
Corrected "it's" to "its", which is the correct form given the context.
Resolves #2744
> Minor comment typo fix

- recipes_source/compiling_optimizer.rst
Add a link to Compiling the optimizer w PT2  dev-discuss post for tech overview:
https://dev-discuss.pytorch.org/t/compiling-the-optimizer-with-pt2/1669
> Add a link to Compiling the optimizer w PT2 dev-discuss

- recipes_source/torch_logs.py
> Update torch_logs.py, fixed a typo in the docs

- .gitignore
Pretty sure we should not be ignoring recipes_source/recipes
Also it keeps messing with my ability to find files in vscode
> Remove recipes_source/recipes from gitignore

- recipes_source/recipes/defining_a_neural_network.py
cc @svekars @brycebortree @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael
> Fixed wrong link of MNIST

- recipes_source/recipes/what_is_state_dict.py
> [Doc]:Add the necessary package of the code

- .jenkins/validate_tutorials_built.py
> Enable parametrizations.py

- advanced_source/usb_semisup_learn.py
The Enabling CUDA link that was added in https://github.com/pytorch/tutorials/pull/2771 was incorrect.
> Fix Enabling CUDA link

- .jenkins/validate_tutorials_built.py
Due to `RuntimeError: DataLoader worker (pid(s) 20092) exited unexpectedly`
> Disable intermediate_source/torchvision_tutorial.py

- beginner_source/PyTorch Cheat.md
Add parentheses to method.
cc @albanD
> Update PyTorch Cheat.md

- advanced_source/privateuseone.rst
Fix the duplicated line in `advanced_source/privateuseone.rst`
```diff
1. Register new backend module to Pytorch.
-2. Generate methods and properties related to the new backend.
+2. Rename PrivateUse1 to a custom name for the new backend.
3. Generate methods and properties related to the new backend.
```
cc @svekars @brycebortree @albanD
> Fix the duplicated line in `advanced_source/privateuseone.rst`

- .github/ISSUE_TEMPLATE/feature-request.yml
Sorry its a nit but was really bothering me :P
> Typo in issue template

- intermediate_source/TP_tutorial.rst
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #2871
cross PR with https://github.com/pytorch/examples/pull/1259
> [Tensor Parallel] update tutorial to simplify embedding + first transformer block

- intermediate_source/dist_tuto.rst
Explicitly mention what the import for `Random()` is in comment
Feedback from: https://discuss.pytorch.org/t/while-trying-to-execute-sample-in-distr-app-tutorial-coding-error-occurs-can-not-fix/203605
cc @wconstab @osalpekar @kwen2501
> Include import for dist_tuto

- beginner_source/transformer_tutorial.rst
Fixes #2895 
cc @sekyondaMeta @svekars @kit1980 @brycebortree
> DEP: deprecate transformer tutorial

- beginner_source/transformer_tutorial.rst
Related to #2895 #2910 and #2922
Re-implements #2929 (accidental deletion from forked repo)
Upon reviewing @svekars changes to #2922, I noticed these weren't correctly implemented in a previous merged PR (#2910) I wrote. I used #2922 as an example and updated changes from #2910
cc @sekyondaMeta @svekars @kit1980 @brycebortree
> FIX: Update `transformer_tutorial.rst`

- recipes_source/recipes_index.rst
- recipes_source/torch_compile_caching_tutorial.rst
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang
> Add tutorial about inductor caching

- recipes_source/intel_extension_for_pytorch.rst
> update Intel(R) Extension for PyTorch Github CPU and GPU branch URL

- beginner_source/knowledge_distillation_tutorial.py
> Fix typo in knowledge_distillation_tutorial.py

- recipes_source/distributed_comm_debug_mode.rst
- recipes_source/recipes_index.rst
This PR is an attempt to re-land #2993 .
> [dtensor][debug] CommDebugMode recipe

- .ci/docker/requirements.txt
> Install torchrec only on Linux

- .github/workflows/link_checkPR.yml
Adding an option to skip checking links on a PR if it has the `skip-link-check` label.
> Update link_checkPR.yml -Add skip link check

- intermediate_source/dist_tuto.rst
Summary:
Minor fixups to the distributed tutorial.
1. Fix broken links.
Test Plan:
Ran the referenced code locally to make sure that it works.
Modernizing distributed tutorial. 
1. Removed broken links 
2. corrected text in various sections.
3. Added more helpful links.
> [doc][c10d] fix up distributed tutorial

- beginner_source/ddp_series_intro.rst
Changing the Author link to the correct github account
> Correct author's github handle

- beginner_source/blitz/autograd_tutorial.py
> fixing issue#2168

- en-wordlist.txt
Add new terms to en-wordlist.txt
* functionalizes
* functionalization
cc @brycebortree @sekyondaMeta @AlannaBurke
> Add new terms to en-wordlist.txt

- beginner_source/onnx/README.txt
This PR updates a broken link to the begginer ONNX tutorial
cc @svekars @brycebortree @sekyondaMeta @AlannaBurke
> Updated broken link on ONNX beginner tutorial

- intermediate_source/reinforcement_ppo.py
> Use DETERMINISTIC sampling in PPO

- CONTRIBUTING.md
example_recipe.py was removed so updating to show an example of a good recipe
cc @svekars @AlannaBurke
> Add link to  a good recipe example

- intermediate_source/transformer_building_blocks.py
> Remove line about nightlies in transformer building blocks tutorial

- beginner_source/introyt/introyt_index.py
Fix broken links in introyt_index.html
cc @sekyondaMeta @AlannaBurke
> Fix broken links in introyt_index.html

- intermediate_source/pinmem_nonblock.py
Fixes tensor description. should be `pageable memory` instead.
> docs/fix tensor description in `Other copy directions`.

- .jenkins/post_process_notebooks.py
Attempt to use a better regex.
> Fix issue with the post-processing script

- intermediate_source/torch_compile_tutorial.py
Addresses https://github.com/pytorch/pytorch/issues/149740
> Add system requirements to compile tutorial

- _templates/layout.html
Removing the docs survey banner
cc @svekars @AlannaBurke
> Remove Docs Survey Banner

- beginner_source/colab.rst
> Fix typos in colab.rst

- beginner_source/basics/README.txt
Fix incorrect filename in README.txt
> Fix incorrect filename

- recipes_source/recipes_index.rst
Fixes [T228127035](https://fburl.com/tasks/7s0rls3r)
> Removing torchserve card from recipes list, per T228127035.

- .jenkins/build.sh
Cleanup directories that contain tutorials before pushing into gh-pages branch
cc @malfet @ZainRizvi
> Cleanup directories before pushing to gh-pages

- .ci/docker/build.sh
We should have update a while back when we've changed the default on PyPI
> Update tutorials image to CUDA-12.6

- beginner_source/basics/intro.py
Fixes #3429 
Fixes a broken link, s/tensor/tensorqs/.
- [X ] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [X ] Only one issue is addressed in this pull request
> Fix a broken link in intro.py

- advanced_source/cpp_export.rst
- advanced_source/torch_script_custom_ops.rst
Fix render failure in 
https://docs.pytorch.org/tutorials/advanced/torch_script_custom_ops.html 
https://docs.pytorch.org/tutorials/advanced/cpp_export.html
> minor fix to render failure in torchscript depcrecation warning

- .ci/docker/requirements.txt
Includes fixes from https://github.com/pytorch/pytorch_sphinx_theme/pull/207
> ci: Change PyTorch Sphinx theme to specific commit

- CONTRIBUTING.md
- README.md
- advanced_source/generic_join.rst
- intermediate_source/rpc_tutorial.rst
- unstable_source/context_parallel.rst
> Fixing Broken Links

- intermediate_source/ensembling.py
- Enhance distributed tutorial: integrate Accelerator API for devise selection
- Integrate the Accelerator API to support multiple accelerators
> Add Accelerator API to ensembling tutorial
