pytorch/tutorials

Deep Learning with PyTorch.ipynb
Make the link to the autograd documentation clickable from the **Deep Learning with PyTorch** notebook
=> Make autograd link clickable

Reinforcement (Q-)Learning with PyTorch.ipynb
By adding "import torch" then we avoid having an error raised when attempting to call:
screen = torch.from_numpy(screen)
=> Updating the imports to avoid error

Deep Learning with PyTorch.ipynb
Fix for broken link in deep learning tutorial (issue #9 )
=> fix link to pytorch slack

Reinforcement (Q-)Learning with PyTorch.ipynb
I'm just learning about PyTorch, but I think the line `param.grad.data.clamp(-1, 1)` has no effect. I guess you wanted to do it *in-place*, which is `clamp_` if I'm not mistaken.
=> Fixed clamp not being applied to parameters

beginner_source/examples_autograd/two_layer_net_autograd.py, beginner_source/examples_autograd/two_layer_net_custom_function.py
In PyTorch 1.10, I think that it is recommended to do zero gradients after updating weights?!
=> fix the issue #51

advanced_source/neural_style_tutorial.py
Replacing usage of `forward()` with call operators like: `model(input)` which is the suggested usage.  [Code](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L205-L222) for details.
=> Use __call__ instead of forward

beginner_source/transfer_learning_tutorial.py
1. Fix #61 
2. Using subplot for displaying predictions
=> Update transfer learning tutorial 

beginner_source/blitz/autograd_tutorial.py, beginner_source/blitz/neural_networks_tutorial.py
A recent refactoring breaks the blitz tutorial. This PR fixes that.
=> Fix errors in beginner/blitz

beginner_source/nlp/advanced_tutorial.py
These two init_hidden are useless. Because they will be called in the _get_lstm_features function.
=> rm useless init_hidden in BiLSTM_CRF

intermediate_source/char_rnn_classification_tutorial.py
rnn has already been initialized before. it's not necessary to reinitialize here. 
Also, this might lead to a bug if using optimizer.step() to update weights without noticing there're two rnn.
=> rnn was initialized twice

beginner_source/nlp/word_embeddings_tutorial.py
I just went through the NLP tutorial - which is awesome btw - and got stuck with the CBOW exercise. I'm fairly new to the topic so excuse me if I am missing out a crucial point here.
Right now, `word_to_ix` is derived from `raw_text`, which causes e.g. the word 'computer' to be indexed with 58.
If understand correctly, the goal is to predict the word which is in the center of 2 context words on each side respectively, causing the probability distribution to contain `len(set(raw_text))` values.
Someone like me who is new to this topic will go ahead and follow the same approach as previously shown in the NGram example:
```python
self.embeddings = nn.Embeddings(len(word_to_ix), embedding_dimension)
```
This will cause the code to break as soon as you hit a `context_vector` containing a word …
=> Added `vocab` and `vocab_size` to CBOW exercise

intermediate_source/char_rnn_classification_tutorial.py, intermediate_source/char_rnn_generation_tutorial.py, intermediate_source/seq2seq_translation_tutorial.py
Previously, processing a single training example was referred to as an "epoch".  I changed this to "step".  A downside of the change is that sometimes "step" is used to refer to a single step of the RNN in processing a training example.  But I don't think there will be too much confusion.
Previously, a function called "randomTrainingSet" in the generation tutorial returned the prepared tensors for a single training example.  I changed the name to "randomTrainingExample".
Previously, a function called "randomTrainingPair" in the classification tutorial returned the prepared tensors for a single training example.  I changed the name to "randomTrainingExample".  The old name also clashed with the use of the name "randomTrainingPair" in the generation tutorial.
A small remaining inconsistency …
=> make some variable and function names more accurate in intermediate RNN tutorials

beginner_source/former_torchies/autograd_tutorial.py, beginner_source/nlp/pytorch_tutorial.py
Follow up to #79, in rest of the files.
=> Fix attribute names (creator -> grad_fn)

intermediate_source/reinforcement_q_learning.py
Alternative to #83.
Fix #66.
~~~WIP.~~~
=> Use cuda on RL tutorial

beginner_source/former_torchies/parallelism_tutorial.py
as described by @jnhwkim [here](https://github.com/pytorch/tutorials/issues/100#issuecomment-311296355), similar to #9 .
=> fixed link to slack in former_torchies/parallelism_tutorial.py

beginner_source/blitz/cifar10_tutorial.py, beginner_source/former_torchies/parallelism_tutorial.py
now pointing directly to /intermediate/reinforcement_q_learning
Fixes the issue reported in #100 .
=> fixed link for "Train neural nets to play video games"

intermediate_source/seq2seq_translation_tutorial.py
I believe "The decoder is given the ``<SOS>`` token as its first input, and the last hidden state of the encoder as its first hidden state."
Minute correction on comment section.
=> Updated comment section at "Training the Model"

beginner_source/nlp/advanced_tutorial.py
Fixing problem in advanced NLP tutorial
=> Fixing #120

advanced_source/super_resolution_with_caffe2.py
We can use map_location to indicate where we should load the data.
If CUDA is unavailable, we should load weights to CPU.
=> Load the weights to CPU if CUDA is not available

beginner_source/pytorch_with_examples.rst
=> Fix small typo in pytorch_with_examples

beginner_source/transfer_learning_tutorial.py
since it normalized the channel value to specific std and mean, when show the image and reverse its value to [0, 1], sometimes it got error of **Floating point image RGB values must be in the 0..1 range.**
use np.maximum() and np.minimum() to restrict the value to [0,1]
=> fix image show error

beginner_source/former_torchies/parallelism_tutorial.py
Fixes a hyperlink linking to `DataParallel` in the API documentation.
=> Fix a link linking to DataParallel

beginner_source/blitz/autograd_tutorial.py
`grad_output` has change to `gradient` in [PyTorch API](https://github.com/pytorch/pytorch/blob/master/torch/autograd/variable.py#L99). 
However this tutorial is still using `grad_output`.
=> Fix 'grad_output' with 'gradient'

beginner_source/blitz/neural_networks_tutorial.py
When running the actual tutorial code as:
```python
output = net(input)
target = Variable(torch.arange(1, 11))  # a dummy target, for example
criterion = nn.MSELoss()
loss = criterion(output, target)
```
It results in an error:
```
...
RuntimeError: input and target shapes do not match: input [1 x 10], target [10] at /tmp/pip-l72ec2wl-build/aten/src/THNN/generic/MSECriterion.c:13
```
Due to the fact that the shape of the `output` is `(1, 10)` and the shape of the `target` is `(10,)`.
This PR updates the shape of the target to be compatible with the output, fixing the error.
=> Fix blitz neural networks shape mismatch

advanced_source/numpy_extensions_tutorial.py
This replaces the calls to `torch.FloatTensor` by a call to `.new` on the input tensor, such that GPU types are respected.
=> Use foo.new instead of torch.FloatTensor for GPU.

intermediate_source/reinforcement_q_learning.py
=> Add target network to DQN

beginner_source/transfer_learning_tutorial.py
Fixes the constant 0 accuracy I get running this tutorial since v0.4
Epoch 0/24
train Loss: 0.8934 Acc: 0.0000
val Loss: 0.7645 Acc: 0.0000
Epoch 1/24
train Loss: 0.6792 Acc: 0.0000
val Loss: 0.2288 Acc: 0.0000
=> Fix epoch accuracy (avoiding integer division)

beginner_source/blitz/data_parallel_tutorial.py
Uses the variable that was defined already in the header, but not used in the source code.
=> Use variable instead of magic number in data_parallel_tutorial.py

requirements.txt
latest pillow version will cause an error(` cannot write mode RGBA as JPEG`) when executing "make docs"
=> change pillow version

advanced_source/numpy_extensions_tutorial.py
Fully correct gradients for the scipy example (checked with torch.autograd.gradcheck).
=> corrected the example for cross-correlation with scipy

beginner_source/blitz/neural_networks_tutorial.py
In [the tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html),
`torch.arange` is being used as a FloatTensor. This behavior was changed
in https://github.com/pytorch/pytorch/pull/7016 to return a LongTensor.
I removed the `torch.arange` usage and instead construct a tensor with
`torch.randn`
cc @SsnL
=> Fix arange in blitz tutorial

beginner_source/blitz/autograd_tutorial.py
The example seems want to say if not specifies, it points to False.
=> Question: requires_grad defaults False?

requirements.txt
That exact dependency was added in #261 at Jun 19. It's unclear to me what version conflicted because it appeared to be the latest released version at that date ( https://pypi.org/project/Pillow/#history ).
The problem is that `scikit-image==0.14.0` requires `pillow [required: >=4.3.0]` (got with `pipenv graph`). So this rule makes it impossible to install the requirements: `Could not find a version that matches Pillow==4.1.1,>=4.1.1,>=4.3.0`.
I started running `make docs` but after 15min it didn't finish the first build so I don't really know how to reproduce the initial error.
=> Remove pillow exact dependency

Makefile
Verbose output helps us track breakages and slow downs. We can remove this once PT1 RC1 is stable.
=> Force verbose output for Sphinx

advanced_source/cpp_export.rst
@JoelMarcey please merge some nits for the tutorial
=> Some nits for the C++ export tutorial

.jenkins/build.sh
This changes the Jenkins script to install CUDA 8.0 Nightly.
=> Update the PT1 Tutorials Jenkins Build script to use CUDA 8.0

beginner_source/chatbot_tutorial.py
On windows machines the default line endings are \r\n instead of \n. This causes code to fail in the filterPair function. Fix details here https://stackoverflow.com/questions/8746908/why-does-csv-file-contain-a-blank-line-in-between-each-data-line-when-outputting
=> Fix line endings in csvwriter for windows machine

advanced_source/super_resolution_with_caffe2.py
onnx_caffe2 and related things are not be used anymore, now we are using caffe2.python.onnx.
=> Removed onnx_caffe2 and related docs, update to caffe2.python.onnx

advanced_source/cpp_extension.rst
The second parameter was wrong which means the name (for error messages) of the kernal. It is repeated with the name of the forward kernel and should be backward kernal.
=> Fix wrong parameter.

.jenkins/build.sh, advanced_source/cpp_export.rst, intermediate_source/spatial_transformer_tutorial.py, requirements.txt
Disabled calculations on spatial_transformer_tutorial.py while we debug some build issues for the tutorial site.
=> Debugging update.

Makefile, README.md
Last run of the build, I saw:
```
02:15:55 make html
02:15:55 make[1]: Entering directory '/var/lib/jenkins/workspace'
02:15:56 Traceback (most recent call last):
02:15:56   File "/opt/conda/bin/sphinx-build", line 11, in <module>
02:15:56     sys.exit(main())
02:15:56   File "/opt/conda/lib/python3.6/site-packages/sphinx/cmd/build.py", line 313, in main
02:15:56     locale.setlocale(locale.LC_ALL, '')
02:15:56   File "/opt/conda/lib/python3.6/locale.py", line 598, in setlocale
02:15:56     return _setlocale(category, locale)
02:15:56 locale.Error: unsupported locale setting
02:15:56 make[1]: *** [html] Error 1
02:15:56 Makefile:21: recipe for target 'html' failed
```
So trying to fix it with an explicit locale set
=> Add `LC_ALL` to force a default locale

beginner_source/chatbot_tutorial.py
I feel how the following filter loss through mask is queationable
assume `batch_size` is `64`, then
`mask` size is `(64)`
`crossEntropy` size is `(64, 1)`
I know you can take use of **[Broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics)**. That's why it can run without exceptions.
However, i guess Broadcasting changes `mask` to `(1, 64)` to work.
Below is sample test how it's wrong
Here I simply squeeze the added dim for `gather`, so their sizes are both `(64)`
=> fix CrossEntropy size in chatbot to align with the mask

advanced_source/torch_script_custom_ops.rst
Custom ops only support a subset of types. Adding some notes about what is supported.
=> Add notes about supported custom ops input types

beginner_source/PyTorch Cheat.md
I fixed some typos in cheat sheet
- from `Dataloader` to `DataLoader` (#381)
- from `Concat Dataset` to `ConcatDataset`
- delete trailing empty line on code block
Please review this PR.
Thanks.
=> fix typo in cheat sheet (#381)

intermediate_source/seq2seq_translation_tutorial.py
All the other apostrophe-containing prefixes have a space after the last character except for "she s" (should be "she s ").
=> Missing space character for an example

Makefile
I've made the following improvements in `download`:
1. Changed all `curl` commands to `wget`.
2. Use all `wget` commands with the `-N` option. Therefore, download and compare the timestamp.
3. All downloaded files are located in the `$(DATADIR)` directory (using `-P` option).
4. A redirect to a null file(`>null`) has been replaced by the `-q` (quiet) option to `unzip`.
5. Removed `sudo` / `chmod`.
6. Unused directories (eg. `data`) have been deleted.
Please review this PR.
Thanks.
=> some improvements to the make download(#384)

beginner_source/nlp/advanced_tutorial.py
- http link works: http://www.cs.columbia.edu/%7Emcollins/crf.pdf 
- but https doesn't: https://www.cs.columbia.edu/%7Emcollins/crf.pdf
=> Fix broken https URL back to http

advanced_source/cpp_export.rst, advanced_source/cpp_frontend.rst, advanced_source/torch_script_custom_ops.rst
Fixed a few C++ API callsites to work with v1.0.1.
TODO: Go through the following two tutorials and find anything that needs to be fixed:
1. https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html
2. https://pytorch.org/tutorials/advanced/cpp_extension.html
=> [v1.0.1] cpp tutorial fix

advanced_source/cpp_export.rst, advanced_source/cpp_frontend.rst
Users following the tutorial on windows had issues when building in debug mode while trying to link to the release DLL. I've added a tip that recommends building from source if they want debug mode.
=> add windows tip to cpp tutorials

beginner_source/blitz/autograd_tutorial.py
Fixes https://github.com/pytorch/pytorch/issues/16352
- Jacobian matrix is corrected (previously represented as its transpose)
- This is in accordance with the usage of vector-Jacobian product mentioned in PyTorch [paper](https://openreview.net/pdf?id=BJJsrmfCZ)
=> Corrects the Jacobian matrix in Autograd tutorial

beginner_source/nlp/sequence_models_tutorial.py
The hidden state is never reused, it's just replaced with zeroes after each use. This is already the default behavior of `nn.LSTM`, so we can drop some code. This change makes it clearer to the beginner (me) that a single `nn.LSTM` call encapsulates the whole rollout of the LSTM.
The output changes slightly for some reason, but it does not look significant. Before:
```
tensor([[-0.0858, -2.9355, -3.5374],
[-5.2313, -0.0234, -4.0314],
[-3.9098, -4.1279, -0.0368],
[-0.0187, -4.7809, -4.5960],
[-5.8170, -0.0183, -4.1879]])
```
After:
```
tensor([[-0.0462, -4.0106, -3.6096],
[-4.8205, -0.0286, -3.9045],
[-3.7876, -4.1355, -0.0394],
[-0.0185, -4.7874, -4.6013],
[-5.7881, -0.0186, -4.1778]])
```
Very useful tutorial by the way! Thanks!
=> Remove unused hidden state in LSTM tutorial

.circleci/config.yml
This tries to fix https://circleci.com/gh/pytorch/tutorials/3919?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.
=> Fix GPG key error

advanced_source/numpy_extensions_tutorial.py, beginner_source/data_loading_tutorial.py
the hyperlink in [restructured text](http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets)  is not the same as markdown. Currently, the rendering is wrong. ( check [here](https://pytorch.org/tutorials/advanced/numpy_extensions_tutorial.html))
=> typo fix & fix hyper link

_templates/layout.html
This PR adds FB Pixel and Google Analytics event tracking. The events that are tracked include clicking "yes" or "no" on the new "Was this Helpful?" section and downloading the source code at the bottom of each tutorial. A Global Site tag has also been added to help with measuring site behavior associated with search marketing campaigns.
=> Wire up FB Pixel and Google Analytics event tracking

_templates/layout.html
This PR updates the FB Pixel and Google Analytics event tracking to deal with the changes from this sphinx theme PR, which adds new download buttons to the tutorials site: https://github.com/pytorch/pytorch_sphinx_theme/pull/43.
=> Update download tracking

index.rst
Path was causing a broken link.
=> Updating colab information link from home page

beginner_source/chatbot_tutorial.py
Provided that: 
```python 
import torch.nn as nn
```
`torch.nn` module name can be replaced with `nn`
=> Replace redundant module names

intermediate_source/model_parallel_tutorial.py
Figures created by `plot.savefig` are shown in deployed version but not in preview. The current version results in two figures for every plot in the deployed version. Use `plt.close` to suppress one.  
[[Preview version](https://deploy-preview-436--pytorch-tutorials-preview.netlify.com/intermediate/model_parallel_tutorial.html)] [[deployed version](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html)]
=> Close figure after plt.savefig

README.md
The link does not work because Sphinx-Gallery's documentation is no longer hosted on Read the Docs.
=> Fix link to Sphinx-Gallery

index.rst
This merge fixes a bug causing STN tutorial to disappear from gallery items
=>  Fix a broken link for STN image

.circleci/config.yml, .jenkins/build.sh, requirements.txt
Trying to fix the following error:
```
May 23 16:08:11 Traceback (most recent call last):
May 23 16:08:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
May 23 16:08:11     out = func()
May 23 16:08:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
May 23 16:08:11     exec(self.code, self.globals)
May 23 16:08:11   File "/var/lib/jenkins/workspace/beginner_source/finetuning_torchvision_models_tutorial.py", line 49, in <module>
May 23 16:08:11     import torchvision
May 23 16:08:11   File "/opt/conda/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
May 23 16:08:11     from torchvision import models
May 23 16:08:11   File …
```
=> Fix torchvision install

advanced_source/super_resolution_with_caffe2.py
This patch is based on #432.
This patch considers the github of caffe2 is moved to its pytorch/caffe2.
=> Fix url for mobile_exporter.py

beginner_source/PyTorch Cheat.md, beginner_source/ptcheat.rst
Shifted the "where for example X is ..." to comments. 
Found it confusing due to sphinx applying bold i.e. ""where **for** example X **is** ..."
=> Commented suggested example variables

advanced_source/ONNXLive.rst
This fix reflects examples #379 changes.
https://github.com/pytorch/examples/pull/379/commits
=> Fix filename for download_saved_models

beginner_source/blitz/neural_networks_tutorial.py
See here for the original comment.
https://github.com/pytorch/tutorials/issues/503
With 5x5 filters and 5*5 dimension from the number of filters that "span" the 32x32 image (after two layers with maxpooling) those numbers were confusing. Hence the filters are changed to 3x3 size.
Possible downsides of this solution:
- We do not cover the image as well, as on the final 2x2 maxpool layer goes over an image of size 13x13, and hence cuts it to 12x12. 
- the comment on line 54 isn't terribly illuminating (but is it kept to a single line).
=> Change to 3x3 conv filters, for ease of reading dimension in net

beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
which is needed when using
```python
device = torch.device("cuda:0")
```
instead of CPU as in the tutorial as
```python
device = torch.device("cpu")
```
=> Add test_seq.to(device) in the hybrid frontend tutorial

beginner_source/blitz/autograd_tutorial.py
Removed mention of `Variable` which is deprecated.
Also, modified a link to the `Function` more detail.
=> remove Variable which is deprecated

advanced_source/numpy_extensions_tutorial.py
We are planning to deprecate legacy autograd function in 1.3.
=> Remove legacy function usgae in numpy_extensions_tutorial.py

beginner_source/PyTorch Cheat.md
Updated the Hybrid frontend section to link to JIT/Torchscript.
=> Update PyTorch Cheat.md

advanced_source/cpp_extension.rst
These are all just names that were inconsistently defined.
=> Fix some minor issues in Custom C++ and CUDA Extensions

.jenkins/build.sh, requirements.txt
Pull request to use binaries from requirements.txt, rather than source installs for torch, torchtext, torchvision, and torchaudio.  Will merge if it passes tests.
=> [WIP] 1.2 binary update

advanced_source/cpp_export.rst
Addressing feedback we got from @SethHWeidman .
Mainly, making sure there's no confusion which serialized model should be loaded in a c++ app.
=> fix confusion w.r.t. which model to serialize and use in cpp_export tutorial

beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
The feedback we got on some other tutorials that we should probably specify the version of PyTorch the tutorial was updated for
=> Add PyTorch version to seq2seq tutorial

advanced_source/torch_script_custom_ops.rst
Fixes https://github.com/pytorch/tutorials/issues/612
=> `torch::jit::RegisterOperators` is being deprecated. Switch to using `torch::RegisterOperators`

beginner_source/data_loading_tutorial.py
Converting the index from `random_split` given in tensor form requested in #540. It seems like a good place to show how a user could enable tensor index.
=> Enabling tensor index from random_split

index.rst
Merge the "Generative" section in with the "image" section.
=> Remove Generative section from tutorials

advanced_source/dynamic_quantization_tutorial.py
@jamesr66a @brianjo Adding `torch.set_num_threads(1)` to create a better comparison between quantized and float models.
=> Update dynamic quantization tutorial

beginner_source/audio_preprocessing_tutorial.py, index.rst
Let's see if the tutorial loads correctly with current binaries. pytorch/audio#307 
This partly reverts commit 9cee82507629c5f557dcef0ed508dc973935ad92 from #685.
CC @SethHWeidman @ezyang
=> Reinstate torchaudio tutorial

advanced_source/cpp_export.rst, advanced_source/cpp_frontend.rst
Targets https://github.com/pytorch/pytorch/issues/30379.
=> Use `cmake --build .` instead of `make`

beginner_source/blitz/autograd_tutorial.py
Flesh out a little bit the last section.
cc @jlin27 because I can't seem to be able to add reviewers here.
=> Update autograd blitz

intermediate_source/dynamic_quantization_bert_tutorial.py
=> Update Dynamic Quant for BERT tutorial

intermediate_source/quantized_transfer_learning_tutorial.py
Summary:
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Fix formatting and clean up tutorial on quantized transfer learning

intermediate_source/dynamic_quantization_bert_tutorial.py
=> Update Dynamic Quant BERT Tutorial 2

intermediate_source/dynamic_quantization_bert_tutorial.py
=> Update Dynamic Quant BERT Tutorial 3

intermediate_source/dynamic_quantization_bert_tutorial.rst
=> Update Dynamic Quant BERT Tutorial 4

.circleci/config.yml
Master CI jobs need access to `context: org-member`, but PR CI jobs don't. So we create two separate sets of jobs for master and PR respectively.
=> Create separate build jobs for PR CI and master CI

beginner_source/audio_preprocessing_tutorial.py
Updating the audio tutorial for the Jan 7 release
- Going to add example in next iteration of tutorial
In a following update of the tutorial, we will want:
Lower priority items:
=> Update audio preprocessing tutorial

advanced_source/cpp_frontend.rst
Changes in this PR:
1. `Conv2dOptions` no longer has `transposed` argument. All use sites of `Conv2dOptions` with `transposed=true` are changed to using `ConvTranspose2d` layers instead.
2. `ConvTranspose2d` layer cannot be used in a `Sequential` module at the moment (see note in PR description of https://github.com/pytorch/pytorch/pull/31005). To get around this problem in the tutorial, we remove the use of `ConvTranspose2d` in a `Sequential` module.
3. For `ConvTranspose2dOptions`, `with_bias` is renamed to `bias`, matching the Python API and following changes in v1.4.0.
4. `torch::nn::Functional` is deprecated in favor of the `torch::nn` equivalent layer, since now we have >80% coverage for `torch::nn` API parity.
5. `torch::nn::BatchNorm` is deprecated in favor of …
=> Update C++ frontend tutorial for v1.4.0

advanced_source/cpp_export.rst, beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
Someone mentioned that they found this confusing, since the current
release is 1.4
=> Remove PyTorch 1.2 notes in tutorials

_templates/layout.html
This PR updates the event tracking for the "Was this Helpful?" button. It uses a different tracking ID and updates the way the data is sent to analytics.
=> Update 'Was this Helpful?' tracking

beginner_source/aws_distributed_training_tutorial.py
The removed lines cause DDP to hang because somehow it triggered
the top layer code to run twice when launching the script from cmd.
Let's see if removing it would pass the CI tests
=> Remove spawn configuration in AWS tutorial

intermediate_source/rpc_tutorial.rst
After recent changes, dist_autograd and dist_optimizer now require context_id to be explicitly passed in. Update that in the tutorial and adjust a few minor comments
=> Update RPC tutorial with new calls to dist autograd and optmizer

README.md
sphinx no longer has a plot_notebook tutorial link. Linking the main 'Notebook style example' page.
=> README.md: Corrected sphinx link

intermediate_source/rpc_tutorial.rst
Removes experimental tag as we removed this from main RPC docs.
=> remove experimental from rpc tutorial

advanced_source/torch_script_custom_classes.rst
This should be included in the 1.5 release along with this cherry-pick PR: https://github.com/pytorch/pytorch/pull/35303
=> Update custom classes tutorial to include namespaces

intermediate_source/torchvision_tutorial.rst
Resolved #1952. Based on the discussion, I have Improved the fast Fast RCNN tutorial by adding more information about the `labels`.
=> Improved  Fast RCNN tutorial 

index.rst, recipes_source/recipes/Captum_Recipe.py, recipes_source/recipes_index.rst
* Add Captum_Recipe.py
* Add captum recipe into the recipes_index.rst
=> Add Captum Recipe into source and recipes_index.rst

recipes_source/recipes/save_load_across_devices.py
Intro-level recipe for saving and loading models across devices in PyTorch. This is 6 of 6 for saving/loading models.
=> Saving and loading models across devices recipe

intermediate_source/ddp_tutorial.rst
As we do not recommend using Single-Process Multi-Device mode with
DDP due to the reduced throughput and as this mode is broken in
v1.5, added this PR to update DDP tutorial to using Multi-Process
Single-Device mode.
This PR also includes the following minor fixes:
1. highlight that this tutorial requires at least 8 GPUs to run
2. added a pointer to RPC
3. added a pointer to torchelastic
4. as DDP now broadcast initial param values from rank 0 to others
it no longer require setting RNG seed.
=> Update DDP Tutorial to remove Single-Process Multi-Device Use Case

recipes_source/recipes_index.rst
Add toc code at the bottom of the recipes_index.rst file to generate breadcrumbs
Built locally and checked through a number of recipes:
=> Add Recipes breadcrumbs

index.rst
=> Minor wording fix

Makefile, conf.py
- Don't clean before running html-noplot (if you want to do a clean
build, just run make clean yourself!)
- Replace filename_pattern with ignore_pattern (with a negative
lookahead assertion).  This means that specifying a GALLERY_PATTERN
will also skip parsing all Python files that you don't care about.
This saves several seconds from the no-op doc build.
- Use distutils to only copy rst files if the mtime is newer than the
destination; this (probably) helps Sphinx avoid recompiling these
files when it's useless.
There are some semantic changes in this diff which is why I'm putting
it up for review.
=> Reduce amount of unnecessary recompilation done by sphinx

advanced_source/dynamic_quantization_tutorial.py, advanced_source/static_quantization_tutorial.py, index.rst, intermediate_source/dynamic_quantization_bert_tutorial.rst, intermediate_source/memory_format_tutorial.py, intermediate_source/named_tensor_tutorial.py, intermediate_source/quantized_transfer_learning_tutorial.rst, intermediate_source/rpc_tutorial.rst, recipes_source/recipes/dynamic_quantization.py
Related to this docs PR to update the feature classification labels: 
https://github.com/pytorch/pytorch/pull/39966
=> Update feature classification labels

.jenkins/build.sh, conf.py, prototype_source/README.md, prototype_source/README.txt
This directory will house all prototype feature tutorials so they won’t be searchable from http://pytorch.org/tutorials since prototype features will only be relevant to a small population of developers and the code will only be in unstable. Once features no longer have the “prototype” classification, they will be graduated to one of the other existing, public-facing directories (e.g. beginner, intermediate, advanced).
=> Add new directory for prototype tutorials

intermediate_source/torchvision_tutorial.rst
pycocotools package fails the tutorial as it doesn't support windows.
Modify the tutorial and refer users to a pycocotools repo that support windows.
=> Modify torchvision_tutorial doc for windows

advanced_source/torch_script_custom_ops.rst, advanced_source/torch_script_custom_ops/CMakeLists.txt, advanced_source/torch_script_custom_ops/op.cpp
I wanted to be able to run the examples easily in this tutorial, so that I could test upcoming changes I'm going to make to it. But this was not easily done because the source code was embedded in the rst file. So what I did was I moved these out to separate files, and then used the `literalinclude` directive to include them back into the rst file. (Gallery wasn't appropriate here because these aren't Python files). This tutorial did a lot of referencing of internal code fragments; I used `start-after` and `end-before` to do these, but I had to goop up the tutorial with some more comments to accurately do these. We could consider stripping these comments out from the final product later, but for now I didn't do it.
You need to install OpenCV somehow to run this test; `conda install …
=> torch_script_custom_ops restructure

advanced_source/torch_script_custom_classes.rst, advanced_source/torch_script_custom_classes/custom_class_project/class.cpp
=> Update torch_script_custom_classes to use TORCH_LIBRARY

prototype_source/distributed_rpc_profiling.rst, recipes_source/recipes_index.rst
Convert RPC recipe into a prototype tutorial. Original recipe PR: https://github.com/pytorch/tutorials/pull/1068/files
Netlify preview here: https://deploy-preview-1078--pytorch-tutorials-preview.netlify.app/prototype/distributed_rpc_profiling.html
=> Make RPC profiling recipe into prototype tutorial

advanced_source/dispatcher.rst, advanced_source/dispatcher/CMakeLists.txt, advanced_source/dispatcher/op.cpp, advanced_source/dispatcher/test.py, index.rst
=> Dispatcher tutorial

.circleci/scripts/build_for_windows.sh
To resolve https://github.com/pytorch/tutorials/issues/1101
memory_format_tutorial.py uses setattr() to modify the attributes of torch. This will cause CI test failure to other tutorials because they are all executed in one process in sphinx.
This bugs will not influence the linux because tutorials are running parallelly with 20 workers on CircleCI for linux and memory_format_tutorial and other related tutorials are running in different workers.
This pr fix it by disable memory_format_tutorial.py when running windows CI test.
test at #1106
=> Disable memory_format_tutorial on Windows CI

intermediate_source/memory_format_tutorial.py
memory_format_tutorial.py uses setattr() to modify the attributes of torch. This will cause CI test failure to other tutorials because they are all executed in one process in sphinx.
So this pr fix it by appending code of recovering attributes of torch to memory_format_tutorial.py.
=> Recover the attributes of torch in memory_format_tutorial

beginner_source/data_loading_tutorial.py, beginner_source/dcgan_faces_tutorial.py
bug in data_loading_tutorial:
This tutorial fails on windows because code with multiple processes must be put in main() function on windows platform. And to not change the structure of the tutorial html page,  just modify the multiple processes to single process.
bug in dcgan_faces_tutorial:
When pytorch updating from v1.5 to v1.6, one warning message "Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported." is changed to error. So change the tutorial correspondingly.
=> fix bugs for data_loading_tutorial and dcgan_faces_tutorial

advanced_source/dispatcher.rst
Now that https://github.com/pytorch/pytorch/pull/42385 is merged, autocast helper functions are available in headers.  The present PR updates the autocast section of the dispatcher tutorial to show their use.
I built the docs locally and they look free from sphinx errors as far as i can tell.
@ngimel @ezyang
=> Update autocast in dispatcher tutorial

intermediate_source/model_parallel_tutorial.py
Spelling mistake led to errors for beginners.
- Browse to https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html#apply-model-parallel-to-existing-modules . second line.
=> Small PR : Corrected model.resnet50() spelling

beginner_source/nlp/pytorch_tutorial.py
The `Introduction to Pytorch` page in the "Deep Learning for NLP" tutorial (https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html), has a typo. This one-line PR fixes the typo.
Before (with typo)
With this PR (typo fixed)
=> Fix typo in "Introduction to Pytorch" tutorial (in NLP tutorial)

recipes_source/recipes/defining_a_neural_network.py
Small update to recipe that instructs users to install `torch` not `torchaudio`
=> Install torch not torchaudio

recipes_source/distributed_rpc_profiling.rst
Addresses @mrshenli 's comments on https://github.com/pytorch/tutorials/pull/1068
=> Address comments on Dist Profiling Recipe

recipes_source/recipes/tuning_guide.py, recipes_source/recipes_index.rst
Initial version of Performance Tuning Guide.
The guide is an extended version based on materials prepared for [ECCV 2020 Accelerating Computer Vision with Mixed Precision Tutorial](https://nvlabs.github.io/eccv2020-mixed-precision-tutorial/) ([slides](https://nvlabs.github.io/eccv2020-mixed-precision-tutorial/files/szymon_migacz-pytorch-performance-tuning-guide.pdf), [recording](https://youtu.be/9mS1fIYj1So)).
=> Add Performance Tuning guide recipe

.jenkins/remove_runnable_code.py
A fix for one line comment when removing runnable code.
=> A fix for one line comment when removing runnable code.

intermediate_source/dynamic_quantization_bert_tutorial.rst
Summary:
Numerics were inaccurate before because of an overflow issue in the kernels. 
Addresses https://github.com/pytorch/pytorch/issues/43016
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Update dynamic quant tutorial for saving quantized model and accurate numerics

advanced_source/dispatcher.rst
Update dispatcher tutorial title to be more descriptive
=> retitle dispatcher tutorial

recipes_source/fuse.rst, recipes_source/model_preparation_android.rst, recipes_source/model_preparation_ios.rst, recipes_source/ptmobile_recipes_summary.rst, recipes_source/quantization.rst, recipes_source/recipes_index.rst, recipes_source/script_optimized.rst
SCRIPT AND OPTIMIZE FOR MOBILE RECIPE for PyTorch Mobile
=> pt mobile script and optimize recipe

prototype_source/vmap_recipe.py
Test Plan:
- Run `vmap_recipe.py` locally
=> Add recipe for prototype vmap

advanced_source/transformer__timeseries_cpp_tutorial/CMakeLists.txt, advanced_source/transformer__timeseries_cpp_tutorial/scheduler.h, advanced_source/transformer__timeseries_cpp_tutorial/transformer_timeseries.cpp
This is Transformer example using CPP frontend
=> CPP Transformer Tutorial

beginner_source/transformer_tutorial.py
This PR updates the transformer tutorial. In the new tutorial, we generate the `src_mask` tensor out of the forward function of the transformer. In this way, users are able to `torch.jit.script` TransformerModel. I have also run the tutorial locally and this PR doesn't change the results and performance.
=> Update transformer tutorial

intermediate_source/speech_command_recognition_with_torchaudio.py
Add command recognition tutorial, see [colab](https://colab.research.google.com/drive/13548KNrwrISdnPEci6a_FyByD60z0aQG).
This pull request complements #572, see also [deprecated tutorial](https://github.com/pytorch/tutorials/blob/d13664e8b5b1baeafb42913f251c27cefa66f000/beginner_source/audio_classifier_tutorial.py).
cc @brianjo
=> Add new speech command recognition tutorial

.circleci/config.yml, .circleci/scripts/build_for_windows.sh
This pr added windows tutorial ci test using cache for saving time and parallizing on 4 workers with each running about 1 hour.
The data directory is cached on CiecleCI with checksum of Makefile and .circleci-weekly as key. This cache will refresh on Sunday or the Makefile changed. This will save the time for downloading data.
=> Add CI test for windows

beginner_source/audio_preprocessing_tutorial.py
One line fix of the link to the documentation as defined in #1233
=> Fixed link to docs in audio_preprocessing_tutorial

beginner_source/examples_autograd/two_layer_net_autograd.py, beginner_source/examples_autograd/two_layer_net_custom_function.py
Fixes https://github.com/pytorch/pytorch/issues/47844
Output before the fix:
```
99 581.02685546875
199 10.408246994018555
299 8.866250991821289
399 21.11296844482422
499 21.725337982177734
```
and
```
99 244.06027221679688
199 11.857839584350586
299 6.741735935211182
399 8.316146850585938
499 18.457813262939453
```
Output after the fix:
```
99 645.8162841796875
199 6.169060707092285
299 0.08816853910684586
399 0.0016538957133889198
499 0.00013183383271098137
```
and
```
99 604.789794921875
199 10.036174774169922
299 0.269910991191864
399 0.009123876690864563
499 0.0006364969885908067
```
=> Fix TF32 convergence issue with TF32

recipes_source/recipes/benchmark.py, recipes_source/recipes/profiler.py, recipes_source/recipes_index.rst
This PR adds a recipe for PyTorch benchmark module.
TODO
cc @robieta, @brianjo, @ngimel
=> Benchmark Recipe

beginner_source/Intro_to_TorchScript_tutorial.py
**Summary**
Tutorials, documentation and comments are not consistent with the file
extension they use for JIT archives. This commit modifies certain
instances of `*.zip` in `torch.jit.save` calls with `*.pt`.
**Test Plan**
Continuous integration.
**Fixes**
This commit fixes #49660 in the pytorch/pytorch repository.
=> [TorchScript] Fix archive file extension in tutorials

beginner_source/dist_overview.rst
The link is missed since the old AWS tutorial is removed.
[PyTorch Distributed Trainer with Amazon AWS](https://pytorch.org/tutorials/beginner/aws_distributed_training_tutorial.html) demonstrates how to use DDP on AWS.
=> remove deadlink of old AWS tutorial

index.rst
Added TorchScript label  to "Introduction to TorchScript" and "Loading a TorchScript Model in C++" tutorials.
=> Added TorchScript label

intermediate_source/quantized_transfer_learning_tutorial.rst
The code was not formatted properly, which caused the subsequent steps to fail
=> [fix] Wrong code formatting

index.rst
3 tutorials were on the left nav, but couldn't be found in the matrix:
- Registering a Dispatched Operator in C++
- Extending dispatcher for a new backend in C++
- (beta) Quantized Transfer Learning for Computer Vision Tutorial
=> Adding tutorials to the matrix

recipes_source/zero_redundancy_optimizer.rst
https://github.com/pytorch/pytorch/pull/53112 updated the argument name from `optim` to `optimizer_class` to match existing argument name in `DistributedOptimizer`. This PR is to update the recipe accordingly. 
This PR also added links to point to `ZeroRedundancyOptimizer` doc page.
=> Update ZeRO recipe to match argument name change

beginner_source/dist_overview.rst
This PR also updates the DDP paper link to point to the official VLDB paper page.
=> Add ZeroRedundancyOptimizer recipe to distributed overview page

index.rst
The Building a Convolution/Batch Norm fuser in FX tutorial (https://pytorch.org/tutorials/intermediate/fx_conv_bn_fuser.html) was added for 1.8. This is a minor update to index.rst to have the tutorial show up in the left hand nav under the "Code Transforms with FX" category.
=> Add new FX tutorial to the left hand nav

.circleci/scripts/build_for_windows.sh
Temp disable fgsm_tutorial for the mnist download issue
It has been disabled in linux at https://github.com/pytorch/tutorials/pull/1415
=> fgsm_tutorial temp disable for windows CI

beginner_source/ptcheat.rst
Added some update to out-of-place tensor operations as well as some updates to
* activation functions
* optimizers
* schedulers
* samplers
CC @jspisak 
Let me know, if these changes look OK and I can add them to the `PyTorch Cheat.md`.
Tagging this PR as WIP for now.
=> [WIP][CheatSheet] update out of place ops, update act fn, optimzers, schedulers, samplers

.circleci/scripts/build_for_windows.sh
The windows package of torchaudio was not uploaded to pytorch channel of conda cloud when CI added for windows, so it was installed from pytorch-test channel. It seems that some failure happen for installing from pytorch-test channel: https://app.circleci.com/pipelines/github/pytorch/tutorials/3747/workflows/dd34f556-4fd7-4073-8b8f-5b8e525d87bd/jobs/70580
And for now torchaudio of windows can be installed from the pytroch channel already. Just fix it.
=> Fix Win CI failure for installing torchaudio

beginner_source/blitz/autograd_tutorial.py
The code at the end registers only the parameters from `model.fc` in the optimizer, although the text underneath says: "Notice although we register all the parameters in the optimizer, the only parameters that are computing gradients (and hence updated in gradient descent) are the weights and bias of the classifier."
To be consistent with this explanation, we should be adding all the parameters from the model.
=> Register all the parameters in the optimizer

requirements.txt
docutils-0.17 causes sphinx-build to fail with:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 69: ordinal not in range(128)
```
Which comes from new https://sourceforge.net/p/docutils/code/8590/tree/trunk/docutils/docutils/writers/latex2e/docutils.sty
=> Pin docutils to 0.16

intermediate_source/torchvision_tutorial.rst
See issue raised here: https://github.com/pytorch/vision/issues/3630
Basically, just copying the selected files cause import errors, since the coco_eval and coco_utils need to be copied as well. 
@NicolasHug pinging you here.
Thanks!
=> Update instructions to copy all files

beginner_source/nlp/pytorch_tutorial.py
When doing this tutorial, I was a bit confused about all of the initial imports. I realized once I'd finished it that I didn't actually need them.
I would recommend removing them to reduce cognitive overload for first-time users.
=> remove unnecessary imports in pytorch_tutorial.py

intermediate_source/README.txt
Link was broken. Updated to new link location. Thanks.
=> Updated web link for flask_rest_api_tutorial.py

beginner_source/blitz/cifar10_tutorial.py
Fixes a formatting typo in the classifier tutorial that is preventing the text referring to the `BrokenPipeError` from being properly rendered as a note. The text is currently being rendered as a code block.
Screenshot of current page:
Screenshot of page after fix:
=> Fix formatting typo in classifier tutorial

beginner_source/Intro_to_TorchScript_tutorial.py
**Summary**
There is a section of the Intro to TorchScript tutorial that is supposed
to illustrate that tracing cannot capture control flow but scripting can.
However, the generated IR for both cases is the same because the tutorial
only prints out the IR for the outer module, not the inner module that
contains the control flow. This commit fixes this issue by printing the IR
for both the inner and outer module to clearly show that tracing does not
capture control flow, but scripting does.
**Testing**
Ran the tutorial file.
Tracing Output:
```
def forward(self,
argument_1: Tensor) -> None:
return None
def forward(self,
input: Tensor,
h: Tensor) -> Tuple[Tensor, Tensor]:
_0 = self.dg
_1 = (self.linear).forward(input, )
_2 = (_0).forward(_1, )
_3 = torch.tanh(torch.add(_1, h, alpha=1)) …
```
=> [TorchScript] Fix Intro to TorchScript tutorial

index.rst
Adding google colab info (https://pytorch.org/tutorials/beginner/colab.html) to the additional resources section on the tutorials home page.
=> Add Google Colab info to the tutorials home page

beginner_source/colab.rst
Minor updates to the instructions on how copy data for use with google colab in order for the example tutorial to run end to end.
=> Update colab instructions

beginner_source/basics/autogradqs_tutorial.py
Ref. [https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)
Attached screenshot.
This PR fixes the typo. Updated text would be 'In order to do that'
=> Fixed typo in Autograd page

beginner_source/basics/data_tutorial.py
Currently, a \`\`blurb\`\` is not being rendered correctly:
This adds a single space character to allow the renderer to successfully parse the input.
You can see rendered output from this fix [here](https://deploy-preview-1482--pytorch-tutorials-preview.netlify.app/beginner/basics/data_tutorial.html#iterate-through-the-dataloader).
=> Fix rendering bug in basics/data_tutorial.py

beginner_source/basics/autogradqs_tutorial.py, beginner_source/basics/buildmodel_tutorial.py
Addresses three grammatical usage errors of "its" (possessive) versus "it's" (contraction.)
Resolves: https://github.com/pytorch/tutorials/issues/1467
=> Fix three usage errors: its vs it's

beginner_source/former_torchies/parallelism_tutorial.py
This updates the link to the torch.nn.dataparallel docs. See https://github.com/pytorch/tutorials/pull/1063.
=> Update link to torch.nn.dataparallel

intermediate_source/parametrizations.py
This PR fixes a couple formatting errors that the tutorial on parametrizations has. In particular, I forgot to put a `super().__init__()` in an `nn.Module`  and a section was being rendered as a comment.
I also took the chance point out explicitly in the tutorial that parametrizations are just Python properties, and I made some minor stylistic changes.
@albanD
=> Parametrizations fix

intermediate_source/flask_rest_api_tutorial.py
typo on Flask tutorial (#1498)
Fix typo: `torchvision-0.3.0` => `torchvision==0.3.0`
=> fix typo on Flask tutorial

beginner_source/basics/autogradqs_tutorial.py
The [latex](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html#optional-reading-tensor-gradients-and-jacobian-products) for the Jacobian matrix is not rendering properly.
It has an extra `\begin{align}` and `\end{align}` tag and this commit removes them.
=> fix latex for Jacobian matrix

advanced_source/cpp_extension.rst, advanced_source/dispatcher.rst, advanced_source/dispatcher/op.cpp
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#1494 Update tutorials for custom inplace & view ops.**
* #1493 Replace AutoNonVariableTypeMode with InferenceMode in user facing tutorial.
=> Update tutorials for custom inplace & view ops.

beginner_source/blitz/cifar10_tutorial.py, beginner_source/blitz/neural_networks_tutorial.py
This PR improves **Deep Learning with PyTorch: A 60 Minute Blitz** > [Neural Networks Tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network)
The following expression is quite confusing for new users
```
x = x.view(-1, self.num_flat_features(x))
```
This line flattens Conv2d output (except of batch dim) before sending it to Classifier.
The best practices here is to use simple `torch.flatten`.
For example, Alexnet uses `torch.flatten` before Classifier
https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py#L48
=> Replace num_flat_features with torch.flatten

intermediate_source/tensorboard_tutorial.rst
This PR fixes [Tensorboard Tutorial](https://github.com/pytorch/tutorials/blob/master/intermediate_source/tensorboard_tutorial.rst).
The tutorial says 
```
navigating to https://localhost:6006 should show the following.
```
Problem is that Tensorboard server does not support `https` protocol. We need to use plain [http://localhost:6006](http://localhost:6006) to open Tensorboard in our browser.
BTW, Other examples use correct http schema:
- [recipes_source/recipes/tensorboard_with_pytorch.py](https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/tensorboard_with_pytorch.py#L112)
- [intermediate_source/tensorboard_profiler_tutorial.py](https://github.com/pytorch/tutorials/blob/master/intermediate_source/tensorboard_profiler_tutorial.py#L157)
=> Fix tensorboard tutorial to use http

recipes_source/recipes/dynamic_quantization.py
Due to extra space in the documentation, the link was displayed incorrectly.
=> Fixed the link in the documentation

advanced_source/rpc_ddp_tutorial/main.py
Replace `emb_rref` with `remote_emb_module`.
Copied from: https://github.com/pytorch/examples/blob/fba20d59beabc144666123db10c907f88e4744b8/distributed/rpc/ddp_rpc/main.py
=> Replace RRef with RemoteModule

beginner_source/basics/data_tutorial.py
Fix https://github.com/pytorch/pytorch/issues/58903
Unify the return value of `FashionMNIST` and `CustomImageDataset ` as tuple.
In the tutorial, `train_features, train_labels = next(iter(train_dataloader))` implies the return value from `DataLoader` is a tuple of image and label. But, before this PR, `CustomImageDataset` returns a dict which makes users confused about our tutorial.
=> Fix dataloader tutorial

intermediate_source/dist_tuto.rst
Fix the comment from describing all-reduce as a point-to-point communication to describing all-reduce as a collective communication.
=> "point-to-point" -> "collective" for describing all-reduce

prototype_source/prototype_index.rst, recipes_source/recipes_index.rst
Adds moved recipe to the correct list.
=> Brianjo mobile int

beginner_source/basics/buildmodel_tutorial.py, beginner_source/basics/data_tutorial.py, beginner_source/dcgan_faces_tutorial.py, beginner_source/text_sentiment_ngrams_tutorial.py, intermediate_source/pipeline_tutorial.py, intermediate_source/seq2seq_translation_tutorial.py, recipes_source/recipes/tuning_guide.py
=> updated pipeline tutorial

beginner_source/text_sentiment_ngrams_tutorial.py
=> updated text sentiment tutorial

beginner_source/saving_loading_models.py
Link previously directed to: https://pytorch.org/docs/stable/nn.html?highlight=load_state_dict#torch.nn.Module.load_state_dict 
Now links correctly to: https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict
Issue: https://github.com/pytorch/pytorch/issues/59856
=> updated load_state_dict link

advanced_source/torch_script_custom_classes.rst, advanced_source/torch_script_custom_classes/custom_class_project/class.cpp, advanced_source/torch_script_custom_classes/custom_class_project/custom_test.py
Error message before this fix
```
terminate called after throwing an instance of 'c10::Error'
what():  Explicitly provided namespace (foo) in schema strng does not match namespace of
enclosing TORCH_LIBRARY block (my_classes).  Move this definition to the (unique) TORCH_LIBRARY block 
corresponding to this namespace (and consider deleting the namespace from your schema string.)  (Error occurred 
while processing TORCH_LIBRARY block at 
/work/dev/tutorials/advanced_source/torch_script_custom_classes/custom_class_project/class.cpp:60)
```
@ezyang
=> Tiny fix of torch_script_custom_classes custom_op namespace and fix of the missing end `}`

recipes_source/fuse.rst, recipes_source/mobile_perf.rst
contiguous never mutates self.  It only returns a contiguous copy if the
tensor is not already contiguous.  Update tutorials to properly capture
this return value and use it for later operations.
=> Fix contiguous usage in tutorials

beginner_source/audio_preprocessing_tutorial.py
Fixed a typo and formatting issue I spotted while going through the tutorial.
Formatting change of bullet points looks like:
Before:
After:
=> Fix small typo and formatting issue

index.rst
Need to update the tutorial description in index.rst (#1605)
I updated [description](https://github.com/pytorch/tutorials/compare/master...9bow:update_tutorial_description?expand=1#diff-54a294a5d016e1a8e98bc95668ed84a99a9edd5c10394d9a2b1ee848006e98a7R165) which is duplicated but not correctly explained.
(And other trailing whitespaces were also eliminated by code editor. 😅 )
=> update text_sentiment_ngrams_tutorial tutorial description (#1605)

advanced_source/rpc_ddp_tutorial/main.py
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #1619
Summary:
w/o the fix, _run_trainer is invoked with rank hardcoded as 2. This introduced [CUDA error: invalid device ordinal]
w/ this fix, _run_trainer will be invoked with rank as 0 and 1 -- those are valid GPU devices.
Example code fix: https://github.com/pytorch/examples/pull/924 
Test Plan:
(pytorch) examples/distributed/rpc/ddp_rpc % python main.py -- run training successfully.
Reviewers:
Subscribers:
Tasks:
Tags:
=> Fix the param: rank --> trainer_rank

advanced_source/generic_join.rst, beginner_source/dist_overview.rst, index.rst, recipes_source/generic_join.rst
I wrote the tutorial as if the feature would be in PyTorch v1.10 (meaning preceding underscores were removed). ~~Here is the PDF of the render:
[render.pdf](https://github.com/pytorch/tutorials/files/6833524/render.pdf)~~ The bot rendered a preview.
This PR is meant as a draft to show what I have for the tutorial. It is not meant to actually be merged any time soon.
=> Add Tutorial for Generic Join Context Manager

beginner_source/basics/autogradqs_tutorial.py
=> fix: Autogradsqs_tutorial typo

beginner_source/basics/buildmodel_tutorial.py, beginner_source/basics/optimization_tutorial.py
This PR is related to issue https://github.com/pytorch/tutorials/issues/1526
A relu layer was inserted just before the cross entropy error was calculated, and it seemed that the loss was not calculated correctly, so I removed the relu layer.
Accordingly, the structure of the NeuralNetwork class in buildmodel_tutorial.py was also changed.
If you have time, I hope you will take a look.
=> fix bug on model definition part of introduction

beginner_source/basics/quickstart_tutorial.py
Adds a `model.train()` call before training.
Because the `model.eval()` is called inside the `test()` function, the model trains in eval mode after the first eopch.
Even though `model.train()` has no effect here because the architecture does not contain batch norm or dropout layers,
A lot of people (myself included) copy code from this tutorial and calling `model.train()` before training is a good practice.
=> [basics/quickstart_tutorial.py] call model.trian() before training

.jenkins/build.sh
By installing newer version of `libgnutls30` that contains a root cert
update
See https://github.com/nodesource/distributions/issues/1266#issuecomment-931481002
=> Fix cert failure during `apt-get update`

recipes_source/recipes/intel_extension_for_pytorch.py, recipes_source/recipes_index.rst
PR to add introduction of Intel Extension for PyTorch to PyTorch tutorials.
=> introduction of intel extension for pytorch

beginner_source/audio_preprocessing_tutorial.py
This resolves issues with audio_preprocessing_tutorial with 1.10 release.
=> Update audio tutorial

beginner_source/examples_autograd/polynomial_custom_function.py
there is a typo in the sample code for [this example](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-defining-new-autograd-functions).  The sample code contains this
```
rimport torch                           #<= this generates an error when attempting to run sample code
import math
```
This PR removes the extraneous "r".
=> Correct typo in example code for autograd example

index.rst, intermediate_source/forward_ad_usage.py
Currently this tutorial is not being rendered at all. This PR places the tutorial in correct directory, adds it to the 'frontend API' index. We also note in the title/description that forward AD is beta (for now), so that users won't be mislead by the current lack of coverage.
After this merges, we can create another PR that updates the name (marked with the correct label).
=> Fix forward AD tutorial directory and add to index

advanced_source/dynamic_quantization_tutorial.py, advanced_source/static_quantization_tutorial.rst, prototype_source/fx_graph_mode_ptq_static.rst
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #1763
Summary: This commit fixes the quantization tutorials such that
they can be run smoothly by the user.
Test Plan: Ran the updated tutorials without problem.
Reviewers: jerryzh168
Subscribers: jerryzh168, supriyar
=> Fix quantization tutorials (imports, syntax, and style)

.circleci/scripts/build_for_windows.sh
`ERROR: Invalid requirement: 'sphinx==1.8.2 sphinx-gallery==0.3.1 docutils==0.16 sphinx-copybutton tqdm numpy matplotlib PyHamcrest bs4 awscli==1.16.35 flask spacy==2.3.2 ray[tune] tensorboard' (from line 1 of requirements.txt)`
The error message tell us that `sphinx==1.8.2 sphinx-gallery==0.3.1 docutils==0.16 ...` are in one line.
=> Make sure line breaks are in generated dependency file

beginner_source/nlp/advanced_tutorial.py
I just fixed a small typo in the advanced_tutorial.py
=> fix typo in advanced_tutorial.py

recipes_source/intel_neural_compressor_for_pytorch.rst, recipes_source/recipes_index.rst
This PR is used to add a guide on how to use Intel(R) Neural Compressor to quantize PyTorch model easily with accuracy-driven auto tuning mechanism.
=> Add Intel Neural Compressor for PyTorch quantization recipes

prototype_source/tracing_based_selective_build.rst
The title format is a bit off. Fix it by adding a line
=> Fix the title format for tracing-based selective build

.circleci/config.yml
Not sure what extra value to they bring, but they take 70+% of CI budget
for tutorials. For example for last 30 days
`machine-windows.gpu.nvidia.medium` cost us 10+M credits, vs
`machine-gpu.medium` less than 4M
=> Disable Windows tutorial builders

beginner/examples_autograd/two_layer_net_autograd.html, beginner/examples_autograd/two_layer_net_custom_function.html, beginner/examples_nn/two_layer_net_module.html, beginner/examples_nn/two_layer_net_nn.html, beginner/examples_nn/two_layer_net_optim.html, beginner/examples_tensor/two_layer_net_numpy.html, beginner/examples_tensor/two_layer_net_tensor.html
https://github.com/pytorch/tutorials/pull/1800 replaced the
obsolete tutorials with symbolic links to the new ones, but
the symbolic links were not correct, and causes deployment error.
https://github.com/pytorch/tutorials/runs/5054296371?check_suite_focus=true
This commit fixes the symbolic links.
https://mthrok.github.io/tutorials/beginner/examples_autograd/polynomial_custom_function.html
https://mthrok.github.io/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html
=> Fix redirect

advanced_source/cpp_extension.rst
Adding documentation about compiling extension with CUDA 11.5 and Windows
Example of failure: https://github.com/pytorch/pytorch/runs/4408796098?check_suite_focus=true
Note: Don't use torch/extension.h In CUDA 11.5 under windows in your C++ code:
Use aten instead of torch interface in all cuda 11.5 code under windows. It has been failing with errors, due to a bug in nvcc.
Example use:
#include <ATen/ATen.h>
at::Tensor SigmoidAlphaBlendForwardCuda(....)
Instead of:
#include <torch/extension.h> torch::Tensor SigmoidAlphaBlendForwardCuda(...)
Currently open issue for nvcc bug: #69460
Complete Workaround code example: facebookresearch/pytorch3d@cb170ac
=> Documenting cuda 11.5 windows issue

.jenkins/build.sh
Build break was caused by an issue with intermediate_source/model_parallel_tutorial.py. I disabled that tutorial to get the build working. This PR enables that tutorial so we can debug the issue.
=> Enables intermediate_source/model_parallel_tutorial.py for testing

intermediate_source/dist_tuto.rst
Fix https://github.com/pytorch/tutorials/issues/1819
=> Fix broken link in dist_tuto.rst

intermediate_source/torchrec_tutorial.rst
Use [substitution references](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-definitions) to style links to TorchRec and PyTorch documentation.
Mark shell script codeblock as shell, rather than python.
=> Fix links in TorchRec tutorial

beginner_source/text_sentiment_ngrams_tutorial.py
- Added `iter` around `AG_NEWS` dataset call since datapipes don't implement a `next` method
- Updated `train_iter` output when calling `next`
- Update vocab transform output
=> Updated text classification tutorial to work with torchtext 0.12.0 release

advanced_source/cpp_extension.rst
Print statement incorrectly stated `us` when it was in `100ms` units.
For clarity I changed it to `s` units and removed the multiplication.
This could have intended to be averaged but total time works just as
well.
=> Fixing timing scheme in cpp_extension tutorial

intermediate_source/speech_recognition_pipeline_tutorial.py
- Remove the mention about the extra axis, which was removed in 0.11 release.
- Cosmetic changes applied on torchaudio repo.
Port from https://github.com/pytorch/audio/blob/main/examples/tutorials/speech_recognition_pipeline_tutorial.py
=> Update Wav2Vec2 ASR tutorial

advanced_source/ddp_pipeline.py, beginner_source/text_sentiment_ngrams_tutorial.py, beginner_source/transformer_tutorial.py, beginner_source/translation_transformer.py, intermediate_source/pipeline_tutorial.py
torchtext datasets starting from version 0.12 depend on TorchData. For 0.12 release, installing torchtext doesn't automatically install torchdata as it is an optional dependency, hence providing explicit message to install torchdata for all the tutorials that access torchtext datasets.
=> add explicit instructions to install torchdata

intermediate_source/FSDP_tutorial.rst
PR fixes the issue with Author name link in [FSDP tutorial](https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html)
=> fix the author name link issue

intermediate_source/torchrec_tutorial.rst
Embedding the introduction to torchrec youtube video (https://www.youtube.com/watch?v=cjgj41dvSeQ) into the corresponding tutorial.
=> Add youtube video to torchrec tutorial

requirements.txt
Jinja 3.1.0 was released yesterday (https://github.com/pallets/jinja/releases). This is causing errors with sphinx 1.8 builds.
=> Pin jinja2 version

.jenkins/build.sh
Getting a dependency error in the master build
Mar 24 18:30:39 Installing collected packages: pillow
Mar 24 18:30:39   Attempting uninstall: pillow
Mar 24 18:30:39     Found existing installation: Pillow 9.0.1
Mar 24 18:30:39     Uninstalling Pillow-9.0.1:
Mar 24 18:30:39       Successfully uninstalled Pillow-9.0.1
Mar 24 18:30:39 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
Mar 24 18:30:39 imageio 2.16.1 requires pillow>=8.3.2, but you have pillow 8.1.0 which is incompatible.
=> Update pillow version in build.sh

.circleci/config.yml
As 16.04 is getting deprecated in May 31st, see this [runlog]( https://app.circleci.com/pipelines/github/pytorch/tutorials/5681/workflows/93c16d30-3559-4414-9eee-879038f881cf/jobs/111635)
Update pinned dependencies correspondingly
=> Update runners to recommended ubuntu-2004

intermediate_source/memory_format_tutorial.py
Hi, I found a typo of image format "NCHW" in the comment.
=> Changed the typo of image format "NCHW"

recipes_source/recipes/loading_data_recipe.py
- `download` parameter is set to `True` so that data is downloaded
- `transform` and `target_transform` parameters are not supported anymore. Hence, removed from the recipe. 
- `root` parameter is undefined in the recipe. Hence `root` parameter value is set to `'./'` so that data is downloaded to the current folder. 
- remove transform parameter related help info in the document
=> updated loading data recipe to use latest api of torchaudio.datasets.YESNO

.circleci/config.yml
Just a proof of concept change, shows how it could be done to avoid wasting `build-manager` cycles waiting for the job to finish.
=> [CircleCI] Make PR build manager dependent on few worker jobs

.circleci/config.yml, .circleci/regenerate.py, .jenkins/build.sh, .jenkins/get_files_to_run.py, .jenkins/metadata.json, .jenkins/remove_runnable_code.py
fixes #1905
helps w/ #1899
Changes:
- convert sharding from bash to python
- create a metadata file to list long running jobs + jobs that require special machines
- shard based on time
- default to 1 min if not a super long time
- only 0th worker uses gpu.nvidia.small.multi
There are three files (can see them in the metadata file) that are long running (20-30 minutes) and are responsible for the unbalance in the shards.  The long run time comes from running a training loop, so we should see what can be done about not running this training loop everytime (perhaps caching the result or reducing the number of epochs)
=> [ci] convert sharding from bash to python

advanced_source/sharding.rst
This commit add the tutorial for exploring torchrec sharding for
distributed model parallelism for embedding tables in large scale deep
learning recommendation systems. We exploring the following sharding:
- table-wise
- row-wise
- column-wise
- data-parallel
=> sharding tutorial for torchrec

.jenkins/get_files_to_run.py
in build.sh they check if " files_to_run " matches " filename ", and if it doesn't it removes the file
get_files_to_run.py was using newlines to separate the file names, not spaces, so it never matched, so the files always got removed 
they have the spaces b/c some file names are substrings of each other
=> use spaces instead of newlines in `get_files_to_run.py`

.jenkins/get_files_to_run.py, .jenkins/test_files_to_run.py
Make `get_all_files` and `calculate_shards` work regardless of the
script invocation cwd
Add `test_files_to_run.py`
Do not leak filedescriptor while reading metadata.json
Use list comprehension instead of list(map(lambda
=> [BE] Small cleanup in get_files_to_run

beginner_source/basics/tensorqs_tutorial.py
Hi all, I just noticed a tiny issue.
The tensor tutorial has a section illustrating standard matrix multiplication vs. element-wise multiplication. In the standard matrix multiplication part, the output array is created with size [5, 4], while the output size will be [5, 5]. This raises a UserWarning:
`UserWarning: An output with one or more elements was resized since it had shape [5, 4], which does not match the required output shape [5, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0).`
Fix is to replace the `rand_like` argument with a tensor of the proper size, like `y1`.
=> Fix matmul resizing UserWarning

beginner_source/examples_nn/polynomial_nn.py
Fix a simple typo that has been bugging me:
=> Fix typo in polynomial_nn.py

beginner_source/translation_transformer.py
- We need to programmatically modify the URLs for the multi30k dataset since the links to the original dataset are broken. 
- We plan to followup with a PR in torchtext that directly updates the URLs in source code, however this PR is still needed to make the dataset work for the 0.13 release (since the torchtext PR will not make it into the latest release)
- Added a commented line to install torchdata (a required dependency to work with torchtext datsets)
=> Updated URLs for Multi30k dataset in translation_transformer tutorial

index.rst, intermediate_source/FSDP_adavnced_tutorial.rst
- Include in index.rst
- Include in what's new
- Limit width to 80 chars
- Fix image
- Remove trailing whitespaces
=> Update FSDP advanced training

.circleci/scripts/build_for_windows.sh, .jenkins/build.sh, requirements.txt
Short 'en' and 'de' names has been deprecated since spaCy 3.0, so use fullname instead as suggested by the warning:
```
[!] As of spaCy v3.0, shortcuts like 'en' are deprecated. Pleaseuse the full
pipeline package name 'en_core_web_sm' instead.
[!] As of spaCy v3.0, shortcuts like 'de' are deprecated. Pleaseuse the full
pipeline package name 'de_core_news_sm' instead.
```
Also, add `--retry 3` to all curl commands in Windows CI path
=> Update spaCy model download to full name

prototype_source/nestedtensor.py, prototype_source/nestedtensor_tutorial.py, prototype_source/prototype_index.rst
This is a beginner tutorial introducing the semantics of nested tensor. Operations are demonstrated through basic examples and a more realistic example (multi-head attention).
Thanks @cpuhrsch for pointing out torch.nn.MultiheadAttention, it is also included in the tutorial to demo how a fused black-box kernel can now be implemented transparently through basic operations.
No training is involved.
This is put under prototype due to nested-tensor ops have to wait for the next PyTorch stable release. Will move to beginner then.
=> add nested tensor tutorial

intermediate_source/torchvision_tutorial.rst
update deprecated `pretrained=True` to `weights="DEFAULT"`
=> torchvision tutorial: update deprecated `pretrained=True`

intermediate_source/speech_recognition_pipeline_tutorial.py
I fixed minor typos mentioned in this issue.(#2008 )
- using using → using
- Creative Commos → Creative Commons
=> fix typos in speech_recognition_pipeline_tutorial.py

intermediate_source/reinforcement_q_learning.py
Gym's domain name has changed since https://github.com/pytorch/tutorials/pull/1928#issue-1247029039
Minor updates to Gym calls, which would produce errors with the latest version of Gym (0.25.2). (possibly fixes https://github.com/pytorch/tutorials/issues/1432#issue-837212016)
Still doesn't train properly as noted in https://github.com/pytorch/tutorials/issues/1755#issue-1071634106 , but at least it runs now as shown in the figure below (didn't touch any other settings in the tutorial).
=> DQN tutorial fixes

Makefile
Its responsible for at least 50% of the lines in our logs
=> make wget less verbose

beginner_source/basics/optimization_tutorial.py
The import `Lambda` is not being used in the example, so I removed it.
=> Remove obsolete import

conf.py, intermediate_source/text_to_speech_with_torchaudio.py
Add `promote_jupyter_magic` to allow embedding install commands into .py file comments
=> Add jupyter cell for deep_phonemizer

beginner_source/ddp_series_multigpu.rst
Adds a note about why set_epoch is useful when training with DDP
=> Add detail about set_epoch in the DDP tutorial series

.jenkins/validate_tutorials_built.py, intermediate_source/reinforcement_q_learning.py, requirements.txt
By adding pygame to the requirements and bumping gym to 0.25.0 (to account for changes introduced by https://github.com/pytorch/tutorials/pull/2026 )
Add cell for installing `gym` on collab
=> Re-enable `reinforcement_q_learning` tutorial

beginner_source/basics/autogradqs_tutorial.py
Shape of gradient argument of `x.backwards` method should be that of `x`.
Modify example, to make input tensor a 5x4 matrix and transpose it in the output
Fixes https://github.com/pytorch/tutorials/issues/2065
=> Update `Tensor Gradients and Jacobian Products` example

intermediate_source/mario_rl_tutorial.py
By switching to new API if gym-v0.25 is used and thus making it more
compatible with gym-v0.26
Also, slightly optimize how tensors are created on CUDA vs CPU devices
=> Update RL Mario Tutorial

intermediate_source/text_to_speech_with_torchaudio.py
Which was unavailable for the couple of days
Fixes https://github.com/pytorch/tutorials/issues/2070
=> Updating WaveGlow checkpoint to latest

beginner_source/blitz/cifar10_tutorial.py
Use `next(iter)` rather than `iter.next()`, which is more Python-3 friendly, that makes tutorial compatible with upcoming 1.13 release, that contains https://github.com/pytorch/pytorch/pull/78594
=> Modernize cifar10_tutorial

requirements.txt
v5.0.0 causes issues with python 3.7: https://github.com/python/importlib_metadata/issues/411
This was raised in the context of https://github.com/pytorch/tutorials/issues/2090
This PR pins the version to <5.0 to circumvent this. Maybe a better fix would be to bump the python version in CI to 3.8, but that's something to discuss more broadly.
=> Pin importlib_metadata<5.0 in requirements.txt

.jenkins/validate_tutorials_built.py, prototype_source/fx_numeric_suite_tutorial.py, requirements.txt
Summary:
Makes a couple of updates to ensure this tutorial still runs on 1.13:
1. add `example_inputs` to `prepare_fx`
Test plan:
Run the tutorial, it runs without errors on master
=> update NS for FX tutorial for PyTorch v1.13

intermediate_source/nvfuser_intro_tutorial.py
Fixes https://github.com/pytorch/tutorials/issues/2093.
Addresses https://github.com/pytorch/tutorials/issues/2093 -- This PR adds a note to clarify the usage of memory_efficient_fusion and make it clearer that the feature is experimental and subject to change.
=> [1.13] Update nvfuser tutorial

intermediate_source/process_group_cpp_extension_tutorial.rst
It covers two changes of c10d introduced in torch 1.13:
- Extract ProcessGroup::Work into a separate class, refer to https://github.com/pytorch/pytorch/pull/83680
- Install c10d headers with absolute path, refer to Install https://github.com/pytorch/pytorch/pull/86933
The tutorial code has also been updated at https://github.com/mrshenli/dummy_collectives/pull/1
=> Update PG backend extension tutorial for 1.13 release

.circleci/config.yml, .circleci/config.yml.in
And delete opt-in `sccache` integration (which hangs unless correct credentials are provided)
TODO: Stop using PyTorch CI docker images, but rather rely in some standard dev docker image
=> Move from Xenial to Bionic as base image

.jenkins/build.sh, .jenkins/validate_tutorials_built.py, prototype_source/maskedtensor_advanced_semantics.py, prototype_source/prototype_index.rst
Continuation of https://github.com/pytorch/tutorials/pull/2052. 
Restructured the PR stack from https://github.com/pytorch/tutorials/pull/2042 
The new format will be:
PR #1: Overview Tutorial
- [Old overview](https://github.com/pytorch/tutorials/pull/2042)
- Why is MaskedTensor useful
- [Distinguish 0 and NaN gradient](https://github.com/pytorch/tutorials/pull/2044)
- [Safe softmax tutorial](https://github.com/pytorch/tutorials/pull/2045)
- [Missing nan ops](https://github.com/pytorch/tutorials/pull/2046)
PR #2: [Sparsity](https://github.com/pytorch/tutorials/pull/2043)
PR #3: [Adagrad sparse semantics](https://github.com/pytorch/tutorials/pull/2047), i.e. what does MaskedTensor make easier -- this one
PR #4: Advanced semantics, e.g. NumPy differences and reduction semantics from [Old …
=> [maskedtensor] Advanced semantics [4/4]

.jenkins/build.sh, .jenkins/validate_tutorials_built.py, prototype_source/maskedtensor_sparsity.py, prototype_source/prototype_index.rst
Continuation from https://github.com/pytorch/tutorials/pull/2050
The new format will be (below are the previous PRs):
PR #1: Overview Tutorial
- [Old overview](https://github.com/pytorch/tutorials/pull/2042)
- Why is MaskedTensor useful
- [Distinguish 0 and NaN gradient](https://github.com/pytorch/tutorials/pull/2044)
- [Safe softmax tutorial](https://github.com/pytorch/tutorials/pull/2045)
- [Missing nan ops](https://github.com/pytorch/tutorials/pull/2046)
PR #2: [Sparsity](https://github.com/pytorch/tutorials/pull/2043) -- this PR
PR #3: [Adagrad sparse semantics](https://github.com/pytorch/tutorials/pull/2047), i.e. what does MaskedTensor make easier
PR #4: Advanced semantics, e.g. NumPy differences and reduction semantics from [Old …
=> [maskedtensor] Sparsity tutorial [2/4]

intermediate_source/reinforcement_q_learning.py
Currently the target network remain fixed during the entire episode.
In this PR I have moved the update of the weigths inside the inner loop of the training. So the update can occure during the episode.
Without this change, if the episode is too long, the target network will be too different from the behavior network.
cc @vmoens @nairbv
=> update target network weight during episode after x timesteps

recipes_source/recipes_index.rst
https://pytorch.org/tutorials/recipes/recipes/profile_with_itt.html is 404.
https://pytorch.org/tutorials/recipes/profile_with_itt.html works.
=> fix broken link issue

intermediate_source/FSDP_tutorial.rst
* rename default_auto_wrap_policy -> size_based_auto_wrap_policy (the interface was changed)
* indentation/imports/etc
=> Update FSDP tutorial

beginner_source/translation_transformer.py, prototype_source/fx_graph_mode_ptq_dynamic.py, prototype_source/fx_graph_mode_ptq_static.rst, prototype_source/fx_graph_mode_quant_guide.rst
Summary: fixing tutorial to have example_inputs and QConfigMapping.
note: the quantization guide leaves example_inputs non initialized that code doesn't seem intended to run and we don't know what teh model is supposed to be.
Test Plan: for fx_graph_mode_ptq_static.rst and
fx_graph_mode_ptq_dynamic.py I pasted and ran the script to verify that it ran, the latter could be run exactly while the former required a slight modification since I didn't had a different version of the imagenet dataset but only the dataloaders had to be modified.
for the quant_guide no explicit testing was done
Reviewers:
Subscribers:
Tasks:
Tags:
Pull Request resolved: https://github.com/pytorch/tutorials/pull/2137
=> [ao] fixing tutorials

CONTRIBUTING.md
Major update to assist user in contributing new tutorials.
=> Assist users in contributing new tutorials

intermediate_source/mnist_train_nas.py
torchmetrics changed the signature of the `accuracy` function in a BC-breaking fashion. This updates the callsite to work with torchmetrics 0.11 and uses `multiclass_accuracy` instead.
cc @dme65
=> Update torchmetrics callsite to fix error due to BC-breaking changes

prototype_source/vulkan_workflow.rst, recipes_source/script_optimized.rst
Update to the following tutorials:
- https://pytorch.org/tutorials/prototype/vulkan_workflow.html
- https://pytorch.org/tutorials/recipes/script_optimized.html
This keeps them aligned with the changes to `optimize_for_mobile` as of https://github.com/pytorch/pytorch/pull/91600
Any changes in this PR which are deletes of space at the end of lines happened automatically when I saved the files
=> Update script_optimized and vulkan_workflow docs with new optimization options

CONTRIBUTING.md, README.md, advanced_source/generic_join.rst, advanced_source/rpc_ddp_tutorial.rst, beginner_source/dist_overview.rst, beginner_source/former_torchies/parallelism_tutorial.py, beginner_source/nn_tutorial.py, intermediate_source/FSDP_tutorial.rst, intermediate_source/ax_multiobjective_nas_tutorial.py, intermediate_source/ddp_tutorial.rst, intermediate_source/dist_pipeline_parallel_tutorial.rst, intermediate_source/dist_tuto.rst, intermediate_source/process_group_cpp_extension_tutorial.rst, intermediate_source/rpc_async_execution.rst, intermediate_source/rpc_param_server_tutorial.rst, intermediate_source/rpc_tutorial.rst, prototype_source/README.txt
While referring to the `CONTRIBUTING.md` as a new contributor, I noticed that the guidelines still reference outdated `Master` branch and its docs. This PR updates Contributing guidelines and other docs to use the latest `Main` branch of the Tutorial repo instead of the `Master` branch.
=> Use Main branch in the docs instead of old Master branch

prototype_source/backend_config_tutorial.rst
Summary: This commit moves the API specification and the Data
Type Restriction sections to the docstrings. See
https://github.com/pytorch/pytorch/pull/91999. This commit also
reorganizes the end-to-end example to make it easier to follow.
Reviewers: jerryzh168, vkuzo
Subscribers: jerryzh168, vkuzo
=> [Quant] Move parts of BackendConfig tutorial

README.md, requirements.txt
Our builds started to fail with the "No module named 'librosa'" error. Adding it to the requirements.txt fixes the issue.
=> Add librosa to requirements.txt

intermediate_source/reinforcement_q_learning.py, requirements.txt
Gymnasium is a fork of OpenAI gym that is developed by the same team that maintained Gym since v0.19-v0.26
You can read more about the reason for the fork in https://farama.org/Announcing-The-Farama-Foundation
In this PR, I have replaced the instances of Gym with gymnasium and removed old code that provided support for Gym v0.25
@vmoens Let me know if there is anything else you would like me to change
=> Replaces `gym` with `gymnasium` in reinforcement learning q-learning tutorial

beginner_source/bettertransformer_tutorial.rst
This PR fixes some minor typos and formatting issues in `bettertransformer_tutorial.rst`. Specifically:
- Fix typo in `improvee`
- Add definition of what `MHA` means. It was mentioned multiple times in the text but it was never explicitly defined (even though it might easily be inferred)
- Add newlines above bullet groups so they're actually rendered as bullets and not as part of the paragraph above it
=> Fix typo and formatting in bettertransformer_tutorial.rst

beginner_source/blitz/neural_networks_tutorial.py
Fixes #787
Moves the aforementioned code block for the [Neural Network notebook](https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/neural_networks_tutorial.ipynb#scrollTo=-H1tj2vB2lFG) into a non-executable block. I also changed the formatting of the weight calculation line, as it wasn't rendering properly in the html. See screenshots below.
cc @suraj813 @svekars @carljparker
=> Move code to non-executable block

.jenkins/validate_tutorials_built.py, beginner_source/hyperparameter_tuning_tutorial.py
Fixes the issue identified in https://github.com/pytorch/tutorials/pull/2185, which allows to re-enable the `Hyperparameter tuning with Ray Tune` tutorial.
___________________
```
WARNING: /home/ubuntu/tutorials/beginner_source/hyperparameter_tuning_tutorial.py failed to execute correctly: Traceback (most recent call last):
File "/home/ubuntu/tutorials/beginner_source/hyperparameter_tuning_tutorial.py", line 428, in <module>
main(num_samples=10, max_num_epochs=10, gpus_per_trial=0)
File "/home/ubuntu/tutorials/beginner_source/hyperparameter_tuning_tutorial.py", line 394, in main
result = tune.run(
File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 365, in run
_ray_auto_init()
File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 878, in …
```
=> Re-enable `Hyperparameter tuning with Ray Tune`

_templates/layout.html
Fixes #1760 
This is a minor one, but I noticed a small typo in the css for the Microsoft Learn links that seems to fix the linked issue.
Before:
After:
Signed-off-by: Kiersten Stokes <kierstenstokes@gmail.com>
=> Fix misalignment of Microsoft Learn links in quickstart tutorial

.circleci/config.yml, .circleci/config.yml.in, .jenkins/get_docker_tag.py
As 11.6 builds has been disabled by https://github.com/pytorch/pytorch/pull/93406
Also, update `.jenkins/get_docker_tag.py` to search for docker folder in `.ci` directory (that was moved there by https://github.com/pytorch/pytorch/pull/93104 ) and raise an error if folder can not be found
=> [CI] Update CUDA to 11.7

beginner_source/ddp_series_fault_tolerance.rst, beginner_source/ddp_series_multigpu.rst, beginner_source/ddp_series_theory.rst, intermediate_source/ddp_series_minGPT.rst, intermediate_source/ddp_series_multinode.rst
As stated in title, this PR fixes a handful of small mistakes in the DDP video series tutorial. It also adds clarification on what GIL is in the [theory](https://pytorch.org/tutorials/beginner/ddp_series_theory.html) page (for those of us new to the concepts 🙂).
Great, tutorial, by the way! Very clear and easy to follow along.
=> Fix minor typos, grammar, and formatting errors in the DDP video series

beginner_source/basics/optimization_tutorial.py, beginner_source/basics/quickstart_tutorial.py
The current logic uses enumerate counter (i.e. variable `batch`). It displays the loss for trained data in an increment of 100 using `if batch % 100 == 0`. i.e. 1st batch, 101 stbatch, and so on for the given dataset. This maps to batch =0, 100, and so on). So for the first batch, the loss displayed should be `[ 64/60000]` instead of `[ 0/60000]`. For the second it should be `[ 6464/60000]` instead of `[ 6400/60000]` , and so on. The values displayed in the `Out:` text box on the tutorial page, e.g. `loss: 2.306185  [ 0/60000]`, read as a loss observed for zero input data which seems incorrect. This loss mentioned here was for the first batch, which was 64 input data. The second was for 101 batch which has 6464 input data, and so on.
cc @suraj813
=> Use the correct batch values in the output

beginner_source/introyt/introyt1_tutorial.py
Fixes #2104 
In going through the [YouTube Intro tutorial](https://pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html?highlight=lenet), I noticed that the dimensions in the LeNet diagram don't match up with code that immediately follows it. Namely, the kernel size should be 5x5 rather than the 3x3 that's given. (And I believe the same should be true for the second convolutional layer?) While not really necessary for the point the tutorial is making, it may reduce confusion for those with no experience with this model (myself included 😄). Especially when comparing with the same network in [this blitz tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html?highlight=lenet) that has the correct kernel size.
cc @suraj813
=> Fix kernel dimensions for LeNet model code example

beginner_source/introyt/trainingyt.py
This PR corrects the formatting of a non-executable block of code in [this tutorial](https://pytorch.org/tutorials/beginner/introyt/trainingyt.html). 
Previously, the code is rendered correctly in the html, but shows up as follows in the notebook file (screenshot from Colab):
With these changes the same block is displayed correctly. The block should remain non-executable, as it is given as an example only and `PATH` is not defined earlier.
Alternatively, I could change the `PATH` variable to `model_path` and change the block into an executable one, but this concept is covered in other tutorials so this may be unnecessary.
cc @suraj813
=> Move code to code block in Youtube "Training with PyTorch" module

beginner_source/basics/autogradqs_tutorial.py, beginner_source/blitz/autograd_tutorial.py
=> Remove links to torchvision finetuning tutorial

.circleci/config.yml, .circleci/regenerate.py, .jenkins/get_files_to_run.py, .jenkins/metadata.json
`torch_compile_tutorial_.py` requires a gpu with capability > 7.1
```
Feb 28 00:20:45 torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Found Tesla P4 which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1
``` 
https://app.circleci.com/pipelines/github/pytorch/tutorials/7439/workflows/fffc8c6e-7f15-4b5b-b843-36d3e7969395/jobs/145263
gpu.nvidia.small has a Tesla P4, which has a compute capability of 6.1, so the PR switches the file to run on gpu.nvidia.medium, which has a Test T4 and a compute capability of 7.5 (https://developer.nvidia.com/cuda-gpus#compute)
This tutorial is actually on the NOT_RUN list, so I'm not actually sure …
=> Make 1st worker gpu.nvidia.medium resource class

beginner_source/introyt/captumyt.py, beginner_source/introyt/tensorboardyt_tutorial.py
This properly formats multi-line commands.
cc @suraj813 @svekars @carljparker
=> Fix command line example formatting by using literal block

.jenkins/validate_tutorials_built.py, beginner_source/introyt/trainingyt.py
Include introyt/trainingyt tutorial in the build
The tutorial was not being built and published on the website.
So fixes such as 7d8cb43 were not then visible on the website since old
output files are still present.
=> Include introyt/trainingyt tutorial in the build

recipes_source/recipes/amp_recipe.py
Replace the incorrect occurences of `torch.cuda.amp.autocast` with `torch.autocast`.
Related issues and PRs in the `pytorch` repository:
https://github.com/pytorch/pytorch/issues/95547
https://github.com/pytorch/pytorch/pull/95760
=> Correct occurences of `autocast` in `amp` recipe

.jenkins/get_sphinx_filenames.py, .jenkins/validate_tutorials_built.py, conf.py
When I did https://github.com/pytorch/tutorials/pull/2034, I mistakenly believed that ignore_pattern just meant that sphinx-gallery would not run the file, instead it actually omits the files from the gallery entirely.  Instead, filename_pattern should be used to determine what is run.  https://sphinx-gallery.github.io/stable/configuration.html#build-pattern
Regex is hard so I decided to give it an entire list of files to run
=> Fix tutorials not running

beginner_source/basics/tensorqs_tutorial.py
Looks like "op" should be "option" here
=> Typo in tensorqs_tutorial.py

intermediate_source/forward_ad_usage.py
Updated the import from the now deleted torch.nn.utils._stateless to torch.func
Fixes https://github.com/pytorch/tutorials/issues/2218
Test Plan:
- tested locally
=> Fix forward mode ad tutorial by updating stateless import

index.rst, intermediate_source/ensembling.py, intermediate_source/jacobians_hessians.py, intermediate_source/neural_tangent_kernels.py, intermediate_source/per_sample_grads.py
As the final step of integrating functorch into PyTorch, we have move the functorch APIs from under functorch.* to torch.func.* and made some adjustments to them.
This PR moves the relevant functorch tutorials from the functorch docs (https://pytorch.org/functorch/stable/) to pytorch/tutorials. We moved four tutorials:
- Jacobians, Hessians, hvp, vhp, and more
- Model ensembling
- per-sample-gradients
- Neural Tangent Kernels.
We also rewrite the tutorials to use the torch.func.* APIs instead of the functorch APIs, and excised mentions of functorch where appropriate.
Test Plan:
- view preview (is that possible for tutorials?)
=> Add torch.func tutorials for PyTorch 2.0

index.rst, intermediate_source/scaled_dot_product_attention_tutorial.py
- Add the 2.0 tutorials to the What's new section
- Minor fixes in the SDPA tutorial
=> Update what's new with 2.0 tutorials

.jenkins/validate_tutorials_built.py, intermediate_source/mnist_train_nas.py
PyTorch lightning 2.0 has a different `Trainer` API which breaks the current training script used in the `ax_multiobjective_nas_tutorial`. Looks like the `pytorch-lightning` dep is not pinned, and so the setup should use the 2.0 version. 
This PR updates the callsite to avoid this breakage.
cc @dme65
=> Update mnist_train_nas script for PyTorch Lightning 2.0 API

recipes_source/recipes/reasoning_about_shapes.py, recipes_source/recipes_index.rst
Tutorial for https://github.com/pytorch/pytorch/issues/97118
=> Add shapes tutorial

beginner_source/dcgan_faces_tutorial.py
=> Fix broken link

intermediate_source/torchserve_with_ipex.rst
It would be good if the multi-worker inference specifies the Torchserve version that can apply ipex.
Related Issues : https://github.com/intel/intel-extension-for-pytorch/issues/323#issuecomment-1502895640
cc @msaroufim
=> add : torchserve version required for multi-worker in ipex

beginner_source/Intro_to_TorchScript_tutorial.py
Fix url to this GIF: https://raw.githubusercontent.com/pytorch/pytorch/main/docs/source/_static/img/dynamic_graph.gif
Currently, the image is not shown in the tutorial.
=> Fix image URL in tutorial Intro_to_TorchScript

intermediate_source/torch_compile_tutorial.py
Make it more clear in the torch.compile tutorial that speedup numbers may be lower than advertised if the GPU is not V100 or A100.
Follow-up to https://github.com/pytorch/pytorch/issues/99939
=> Add note and check for GPU capability

beginner_source/dist_overview.rst
The hyperlink to `generic_join.rst` was missing the "j", resulting in a 404 error.
=> Fix typo in dist_overview.rst

prototype_source/torchscript_freezing.py
Small typo in `prototype_source/torchscript_freezing.py`, editing to fix `SciptModule` -> `ScriptModule`
=> Fix typo in `torchscript_freezing.py` comment: `SciptModule` -> `ScriptModule`

.github/workflows/docathon-assign.yml
Adding a workflow that allows users with no permissions assign issues to themselves by commenting on an issue: "/assigntome".
=> Add the assign workflow

.github/scripts/docathon-label-sync.py, .github/workflows/docathon-label-sync.yml
Add a GH action that propagates labels from the issue to PR. The issue must be tagged with the docathon label.
=> Propagate labels from the issue to the PR

intermediate_source/char_rnn_classification_tutorial.py, intermediate_source/char_rnn_generation_tutorial.py, intermediate_source/seq2seq_translation_tutorial.py
=> Fix links to Author profile

advanced_source/neural_style_tutorial.py
Fixes #1736 
Set model to evaluation mode along with requires_grad_(False) in Neural Style Transfer tutorial.
=> Add model.eval() in neural_style_tutorial.py

beginner_source/introyt/trainingyt.py, intermediate_source/torchvision_tutorial.rst
Fixes #2230
Fix the comment and related code for the test step to enhance clarity and accuracy.
cc @suraj813
=> Fix train loop in trainingyt.py

beginner_source/blitz/cifar10_tutorial.py, beginner_source/deep_learning_60min_blitz.rst
Fixes #940 
Added matplotlib to the list of necessary packages for running the tutorials in "Deep Learning with Pytorch: A 60 Minute Blitz". The "Training a Classifier" tutorial requires matplotlib package for showing training images.
https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
=> Added matplotlib dependency to blitz tutorial

prototype_source/fx_graph_mode_quant_guide.rst
Fixes #2337
Fix formatting in the tutorial: https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide
=> Fix formatting in the FX Graph Mode Quantization guide

beginner_source/transformer_tutorial.py
Fixes #1037 
Changed the text,
> we would divide the alphabet into 4 sequences of length 6
to 
> we would divide the alphabet into sequences of length 6, resulting in 4 such sequences
With this, the reader knows that a tensor of shape (seq_length, batch_size) is being created, which is consistent with the shape of the tensor returned by the `batchify` function
=> Change batchify desc to remove ambiguity

intermediate_source/tensorboard_profiler_tutorial.py
Fixes #1901
After these changes, the HTML is being rendered as it was before (expected behavior), but the corresponding code blocks in the Colab notebook will be rendered properly.
Before (following link from tutorial HTML):
After (rendered in VSCode):
=> Change formatting of code blocks in Tensorboard profiler tutorial

prototype_source/README.txt
Fixes #2312
Update unreachable link to point to current document instead of specific old version.
Also, fix tabs to be consistent in whole document.
=> README.txt - fix unreachable link

beginner_source/introyt/tensorboardyt_tutorial.py
Fixes #1919 
The following error occurs when running the notebook in Google Colab (which has TensorFlow installed):
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-cff6eb059fb9>](https://localhost:8080/#) in <module>()
16 writer.add_embedding(features,
17                     metadata=class_labels,
---> 18                     label_img=images.unsqueeze(1))
19 writer.flush()
20 writer.close()
[/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py](https://localhost:8080/#) in add_embedding(self, mat, metadata, label_img, global_step, tag, metadata_header)
808         save_path = os.path.join(self._get_file_writer().get_logdir(), subdir)
809 
--> 810 …
=> Fixes module 'get_filesystem' error

intermediate_source/mario_rl_tutorial.py
Fixes #1607
This PR makes a few changes in order to render a non-empty plot in the doc HTML.
- Ups the number of episodes run so that there are enough data points to plot (w/ 10 episodes, only one data point would be available due to a save every 20)
- Clears the plot at the beginning of the loop that plots all 4 metrics; this ensure the plot is not cleared on the final iteration and results in something being displayed
- Adds a legend to the plot so that the rendered image contains some context and isn't just a random straight line
New rendering:
cc @vmoens @nairbv @svekars @carljparker
=> Render a non-empty plot in Mario-RL tutorial

beginner_source/nn_tutorial.py
Fixes #1757 
The commit removes redundant iter() calls in the WrappedDataLoader class, optimizing the iteration process. Previously, iter() was called when initializing the iterator and again within the for loop, which was unnecessary. The code is now clearer and more efficient by eliminating the redundant call.
Previously
```python
def __iter__(self):
batches = iter(self.dl)
for b in batches:
yield (self.func(*b))
```
Modified
```python
def __iter__(self):
for b in self.dl:
yield (self.func(*b))
```
cc @suraj813 @svekars
=> Optimize DataLoader iteration in WrappedDataLoader

intermediate_source/char_rnn_classification_tutorial.py
Fixes #193
- Address issue described Err in char_rnn tutorial;
- Also did a small amount of text only editing / cleanup missing links to related tutorials, correct a subtitle
=> Address Err in char_rnn tutorial issue

.github/workflows/docathon-label-sync.yml
Fixes #2083 
Added `model.eval()` in test loop and comments to explain what `model.eval()` does. Added additional comments before `torch.no_grad()` to explain the differences between `model.eval()` and `torch.no_grad()` and their uses. 
Changes: 
```python
def train_loop(dataloader, model, loss_fn, optimizer):
....
model.train()
.....
def test_loop(dataloader, model, loss_fn):
model.eval()
.....
with torch.no_grad():
.....
```
cc @suraj813
=> Resolving issue#2083

.github/workflows/docathon-label-sync.yml, beginner_source/introyt/introyt1_tutorial.py
Fixes #1818
Modified `transforms.Normalize` mean and standard deviation values to reflect CIFAR10 train mean and standard deviations
from 
```python
transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
```
to 
```python
transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))])
```
Modified the docstring to reflect the change, that the new mean and standard deviation will be 0 and 1, respectively. Also, additional details were added to explain how those values were generated: 
```python
#
```
cc @suraj813
=> resolve issue 1818 by modifying mean and standard deviation in the transforms.Normalize

beginner_source/data_loading_tutorial.py
Fixes #876
I have updated image cropping lines to include last row and column. Earlier the top index was from `[0, h - new_h)` where `h` is the height of the image and `new_h` is the height of the cropped image. 
Consider a case where `new_h = 3` and `h = 4`. In this case, top index can only be 0 and hence the last row will never get started. To fix this, I have updated `np.random.randint` to sample from `[0, h - new_h + 1)` for choosing last row and for chosing last column, I have update the func to sample from `[0, w - new_w + 1)`
=> Fix cropping to include last column and last row

intermediate_source/char_rnn_generation_tutorial.py
Fixes #844
Changed the loss initialization from 0 to torch.Tensor([0]) in order to avoid confusion about the dtypes.
cc @svekars @carljparker @kit1980
=> Fix the loss initialization in intermediate_source/char_rnn_generation_tutorial.py

beginner_source/transformer_tutorial.py
Add description for positional encoding calculation for Transformers
Fixes #1778
Add explanation for calculating positional encoding for Transformers by taking the log first and then applying the exponential function.
cc @suraj813
=> Update transformer_tutorial.py | Resolving issue #1778

intermediate_source/ddp_tutorial.rst
Fixes #1750
Fixes run_demo(demo_model_parallel, world_size) issue as described in #1750
cc @mrshenli @osalpekar @H-Huang @kwen2501
=> Fix run_demo(demo_model_parallel, world_size) issue

beginner_source/introyt/captumyt.py
Fixes #2290 
The following changes are proposed:
1. Flask-compress is explicitly installed because it is needed for the Captum Insights example. It is not installed in Google Colab, although `flask==2.2.4` is there.
2. `matplotlib==3.3.4` ([ref](https://github.com/pytorch/captum/issues/1136#issuecomment-1540202585)) is installed because Captum uses an older version of a matplotlib function whose arguments have been renamed recently. Check the following stack trace to confirm:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-12-3e00f13e4ddc>](https://localhost:8080/#) in <cell line: 2>()
1 # Show the original image for comparison
----> 2 _ = viz.visualize_image_attr(None, …
=> Fix dependencies and kernel crash in captumyt.py

recipes_source/recipes/changing_default_device.py
We are using sphinx to render those tutorials, which does not start a new process to render, so one needs to restore global state to default value, by calling `torch.set_default_device('cpu')`
=> Set global device back to cpu at the end of tutorial

beginner_source/dcgan_faces_tutorial.py
By using deterministic algorithm
That should prevent repo size increase by 70Mb after every commit, but will make tutorial generation slightly slower (from 35 to 41 min)
Also, remove unused/absolete imports
=> Make DCGan tutorial results reproducible

beginner_source/transformer_tutorial.py
Fixes #1877 
The tutorial is using a transformer encoder and the mask used was for masking a decoder which is not part of the tutorial.
The mask is removed. Some variable names are changed to better reflect the purpose of the variable. Also, some unused imports are removed.
cc @pytorch/team-text-core @Nayef211
=> Remove improper src_mask from encoder tutorial

intermediate_source/dynamic_quantization_bert_tutorial.rst, prototype_source/graph_mode_dynamic_bert_tutorial.rst
Remove `global_rng` and use `torch.randint` to feel the tensor of shape `shape` with values in range `[0, vocab_size)`
=> [BE] Simplify `ids_tensor`

intermediate_source/torch_compile_tutorial.py
I noticed when reading through these docs that the two examples did not use the parameter 'y'. I assume it was meant to be used so I updated the code in the examples. Another possibility is that we don't need param 'y' and only need 'x'. Let me know if that is the case and I will fix this :)
=> Update torch_compile_tutorial.py to use unused parameter

advanced_source/neural_style_tutorial.py, conf.py, recipes_source/recipes/changing_default_device.py
To make tutorial builds predictable, but still keep randomness when one rans it on Collab.
Also, reset default_device after every tutorial run
=> Set random seed

intermediate_source/torch_compile_tutorial.py
"evaluating and training ResNet-18 on random data" --> "evaluating and training a ``torchvision`` model on random data", since speedups are no longer demonstrated on resnet18.
=> Fix typo in torch_compile_tutorial.py

intermediate_source/seq2seq_translation_tutorial.py
Fixes https://github.com/pytorch/tutorials/issues/1642
cc @pytorch/team-text-core @Nayef211
=> Change paper reference to a paper matching the model used

prototype_source/quantization_in_pytorch_2_0_export_tutorial.rst
Following up of https://github.com/pytorch/tutorials/pull/2354.
Modify the Descriptions in document of `quantization_in_pytorch_2_0_export_tutorial`.
=> modify quantization in pytorch.2.0 export tutorial

beginner_source/text_sentiment_ngrams_tutorial.py
Fixes #1993 
Issues were observed executing Text classification with the torchtext library tutorial.
To mitigate it, especially in Google Collab environment, prerequisite for installing proper version of portalocker library is needed.
Added this prerequisite to tutorial description.
cc @pytorch/team-text-core @Nayef211
=> Mention prerequisites for running tutorial basing on observations

intermediate_source/seq2seq_translation_tutorial.py
Fixes #2121 
Redefines the attention mechanism and decoder network from the tutorial [NLP From Scratch: Translation with a Sequence to Sequence Network and Attention](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html).
Due to merge conflicts, I had to close PR #2427, however I addressed the feedback received in my last PR.
=> Sequence to sequence encoder-decoder attention

.github/workflows/build-tutorials.yml
Should prevent crashes during NCCL initialization.
If `data_parallel_tutorial.py` is executed without this option it would segfault in `ncclShmOpen` while executing `nn.DataParallel(model)`
For posterity:
```
% nvidia-smi 
Fri Jun 16 20:46:45 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+========= …
```
=> [CI] Spawn docker container with 2Gb shmem

conf.py
Adding torch.cuda.empty_cache() to the reset_seeds function to solve CUDA out of memory error when adding the Inductor tutorial.
=> Add torch.cuda.empty_cache() to the reset_seeds function

intermediate_source/process_group_cpp_extension_tutorial.rst
Update tutorial to use `Backend` instead of `ProcessGroup`. The extension of ProcessGroup is not recommended anymore and users should use `Backend` as a more flexible alternative.
Fixes a task in https://github.com/pytorch/pytorch/issues/90544
Update tutorial to point to a correct custom C++ extension example: https://github.com/H-Huang/torch_collective_extension
=> Update process_group_cpp_extension tutorial for dispatching to backends

intermediate_source/torch_compile_tutorial.py
This PR removes duplicated code `compile_times = []` in `torch_compile_tutorial.py`
cc @williamwen42 @msaroufim
=> remove duplicated code in torch_compile_tutorial.py

.jenkins/build.sh, requirements.txt
`/opt/conda/bin` folder contains default Python (3.11 after the last update) rather than the one specified promised by the docker container (which is installed in the environment)
Remove explicit `PATH` to stick to Python-3.10 installed as part of the container (as `torchx` is yet not available for Python-3.11)
Also, uninstall `ghstack` to prevent downgrade `importlib-metadata` from `6.8.0` to `3.X`.
Pin `importlib-metadata`, `scipy`, `numba` versions. 
Minor: Add `--progress-bar off` option, to keep logs readable.
=> Fix tutorial dependencies install

.jenkins/validate_tutorials_built.py
Temporarily disable the T5 tutorial to fix the issue with the dataset that can't be downloaded because the website is down. More info: https://github.com/pytorch/text/issues/1756
=> Temporarily disable the T5 tutorial

prototype_source/pt2e_quant_ptq_static.rst, prototype_source/pt2e_quantizer.rst
=> [quant][pt2e][tutorials] Some fixes to pt2e quant docs

prototype_source/pt2e_quant_ptq_static.rst
- Wrap lines at 79 chars
- Remove numbering from headings
- Fix typos
- Fix formatting
=> Editorial changes to the pt2e tutorial

recipes_source/recipes/tuning_guide.py
By default, conv-bn folding isn't done with CNN based models when AMP is used with oneDNN Graph. `torch.fx.experimental.optimize.fuse` should be used for such models
=> conv-bn folding should be used for CNN-based Vision Models when AMP is used with oneDNN Graph

prototype_source/pt2e_quant_ptq_static.rst
Summary:
att
Test Plan:
visual inspection of generated pages
Reviewers:
Subscribers:
Tasks:
Tags:
=> [quant][pt2e] Update save/load model for pt2 export quant tutorial

intermediate_source/torch_compile_tutorial.py
Fix this build error: https://github.com/pytorch/tutorials/actions/runs/6053797611/job/16430000451#step:8:5074
=> Fix torch.compile tutorial for 2.1 release

.jenkins/get_files_to_run.py, .jenkins/metadata.json
Should fix the fact that I run into tutorial build issues when the sharding algorithm punts the tutorial to a different worker that has too old of a GPU. 
```
RuntimeError: Found Tesla M60 which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 5.2
```
Error logs: https://github.com/pytorch/tutorials/actions/runs/6281857867/job/17060687817
=> SDPA tutorial requires newer CUDA, so host it on an A10G

prototype_source/numeric_suite_tutorial.py, recipes_source/recipes/Captum_Recipe.py
For TorchVision models, `pretrained` parameters have been deprecated in favor of "Multi-weight support API" - see https://pytorch.org/vision/0.15/models.html
=> [TorchFix] Update deprecated TorchVision `pretrained` parameters

.jenkins/download_data.py, Makefile
- `download_url_to_file` which is heavily inspired by [torch/hub.py](https://github.com/pytorch/pytorch/blob/efb73fe8e4413a0d6db078e85c7ed7c91f05ca5d/torch/hub.py#L600)
- `size_fmt` is borrowed from [torch/autograd/profiler_util.py](https://github.com/pytorch/pytorch/blob/efb73fe8e4413a0d6db078e85c7ed7c91f05ca5d/torch/autograd/profiler_util.py#L372)
- Skip  downloads if `FILES_TO_RUN` is defined, but tutorial is not in this shard, i.e.:
- Call `download_dcgan_data`(which is 1Gb+ downloadable) only for  `dcgan_tutorial `
- Call `download_lenet_mnist`(downloads from rate-limited GDrive) only  for `fgsm_tutorial`
- Call `download_hymenoptera_data` only for `transfer_learning_tutorial`
- Call `download_nlp_data` for `seq2seq_translation_tutorial`, `char_rnn_classification_tutorial` and …
=> [BE] Move data download logic to `download_data.py`

Makefile, requirements.txt
Followup after https://github.com/pytorch/tutorials/pull/2154 that moved audio tutorials to another repo
- Do not install `torchaudio`
- Do not download `UrbanSound8K.tar.gz`, which is 5+Gb
=> [BE] Do not download audio assets

.jenkins/validate_tutorials_built.py, _templates/layout.html, beginner_source/onnx/README.txt, beginner_source/onnx/intro_onnx.py, index.rst
This PR adds a `Backends` section to the left menu which initially will have a placeholder for the series of ONNX export tutorials based on Torch Dynamo backend
A table of content tree page will have static URL `https://pytorch.org/tutorials/beginner/onnx/intro_onnx.html` that will be referenced on PyTorch user document for `torch.onnx module`
Following is a screenshot of the resulting page
Preview page: https://docs-preview.pytorch.org/pytorch/tutorials/2550/beginner/onnx/intro_onnx.html
Fixes: https://github.com/pytorch/tutorials/issues/2552
=> [ONNX 1] Add Backend section to the left page of Tutorials layout page

requirements.txt
As latests seems to be incompatible with latest tensordict release, see https://github.com/pytorch/rl/issues/1606
=> Pin torchrl deps to 0.2.0

intermediate_source/torch_compile_tutorial.py
Fixes https://github.com/pytorch/pytorch/issues/110666.
Moved placement of `torch.no_grad`. Added asserts for speedup values so that future regressions are detected sooner.
=> Fix eval compile timing in torch.compile tutorial

intermediate_source/tensorboard_profiler_tutorial.py
There is a bug when combining with_stack=True and repeat>1. So we set repeat=1 for this example. Also, I've added notes that tensorboard plugin is being deprecated, and replaced by HTA. We will have a new tutorial for using HTA in the upcoming months.
Fixes https://github.com/pytorch/pytorch/issues/109969
cc @chaekit
=> [docathon] Update tensorboard_profiler_tutorial.py to work

intermediate_source/torch_compile_tutorial.py
Add link to PT2 benchmarks for official speedup numbers.
Replace `evaluate` function by calling the model/optimized model.
=> Small fixes to torch.compile tutorial

prototype_source/pt2e_quantizer.rst
Summary:
att
Test Plan:
CI
Reviewers:
Subscribers:
Tasks:
Tags:
=> [quant] Add IR related recommendations for Quantizer tutorial

prototype_source/semi_structured_sparse.rst
I was running [this tutorial](https://pytorch.org/tutorials/prototype/semi_structured_sparse.html) on 2:4 sparsity and found a few issues that I'm fixing in this PR. More concrete:
1. Block with the model definition wasn't rendered on the website since there was some stop symbol in source markdown. 
2. One variable wasn't defined in the code and one comma was missed in another place -- so some code wasn't working.
3. Model didn't converge to the same level of performance after pruning (gap was substantial in F1 metric). The problem seems to be related to the learning rate schedule in HuggingFace Transformers: during fine-tuning of pruned model learning rate went to 0 super quickly and the model params were not updating at all. To fix it I simply set LR schedule to constant, so we have …
=> Implemented fixes in 2:4 sparsity tutorial

README.md
- Add instructions to run `python3 -m torch.utils.collect_env` and posting the output in the body of the bug.
- Redirect questions to dev-discuss
=> Add instructions on asking questions and submitting bugs

requirements.txt
See https://github.com/pytorch/tensordict/issues/547
Should fix https://github.com/pytorch/tutorials/actions/runs/6659680370/job/18099294856 and prevent tutorials CI regress from the sudden updates of the dependencies
=> Pin tensordict to 0.2.0

prototype_source/pt2e_quant_ptq_x86_inductor.rst
Add x86InductorQuantizer Performance Number.
=> Add x86InductorQuantizer Performance Number

intermediate_source/FSDP_adavnced_tutorial.rst
The current links are poiting to older examples on an individual repo. This PR replaces those links with the PyTorch upstream examples repo. Also, adding consistency in how examples are referenced to point to the links.
Fixes #2447
cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> Change links to the newest examples

recipes_source/recipes/tuning_guide.py
A couple of "for more details" links to external sites are no longer finding details. Better to remove them.
Fixes #2629 
The current suggestion was to remove the links.  It is better to not suggest more details when the links destinations move.
cc @svekars @carljparker @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @sekyondaMeta @NicolasHug @kit1980 @subramen
=> Remove broken links in tuning guide

advanced_source/static_quantization_tutorial.rst
The link says most of the code is from "here", but it goes to mobilenet.py which is just imports. Most of the code comes from mobilenetv2.py.
Fixes #2637
Updating one "here" link.
The link says most of the code is from "here", but it goes to mobilenet.py which is just imports.
Most of the code comes from mobilenetv2.py.
This is the first link under https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#model-architecture which includes significant code for class MobileNetV2.
As someone trying to follow the tutorial and use those links, it would make more sense to go to mobilev2.py.
cc @svekars @carljparker @sekyondaMeta @NicolasHug @kit1980 @subramen
=> Update static quantization tutorial code link to go to mobilenetv2.py

intermediate_source/mario_rl_tutorial.py
Fixes #2335
Removed copy.deepcopy method with appropriate torch methods on intermediate_source/mario_rl_tutorial.py file
cc @vmoens @nairbv @albanD @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> Fix mario_rl_tutorial.py

intermediate_source/mario_rl_tutorial.py
Fixes #2651
Improved the episode functionality by ensuring that episodes are logged properly, preventing unnecessary episode runs without logging.
cc @vmoens @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> Add logging to last episode

intermediate_source/mario_rl_tutorial.py
Fixes #2650
Enabling antialias for compatibility with newer versions of PyTorch.
cc @vmoens @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> Enable antialias on marioRL

beginner_source/introyt/tensorboardyt_tutorial.py
Fixes #1756
Corrected the comment mentioning the use of `.train(True)` and `.train(False)`.
cc @suraj813 @aaronenyeshi @chaekit @jcarreiro @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> corrected comment regarding .train and .eval

prototype_source/pt2e_quant_ptq_x86_inductor.rst
Add usage of int8-mixed-bf16 quantization in X86InductorQuantizer.
cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen
=> Add usage of int8-mixed-bf16 quantization with X86InductorQuantizer

intermediate_source/reinforcement_q_learning.py
Tutorial uses index numbers to access the values of named tuple returned from torch.max() which is a little unclear. This changes it to use the names "indices" and "values" instead. This is a trivial change so I did not make a separate issue.
cc @vmoens @nairbv
=> Update reinforcement_q_learning.py - use named tuples rather than indices

intermediate_source/reinforcement_q_learning.py
I realized that the link for Gymnasium cannot be accessed because of typo.
Now, you can access the gymnasium website by hyperlink!
=> Small typo in DQN tutorial

.jenkins/build.sh, .jenkins/validate_tutorials_built.py
Temporarily pull 2.2 binaries.
=> Install 2.2 RC binaries

.jenkins/validate_tutorials_built.py
Disabling the advanced_source/usb_semisup_learn.py as it takes 140 minutes to build.
=> Disable usb_semisup_learn.html

.jenkins/validate_tutorials_built.py, intermediate_source/torch_export_tutorial.py
Copy over the nightly tutorial for the 2.2 release, since there were API changes since 2.1.
Will fix https://github.com/pytorch/tutorials/issues/2707
=> Update torch.export tutorial for 2.2

_static/css/custom2.css, _templates/layout.html, conf.py
- Temporarily add a link to the tutorials survey on all pages
=> Temporarily add tutorials survey

recipes_source/recipes_index.rst
1. Fix the "customcarditem" for DCP in recipes_index.rst
2. Fix the incorrect link
=> [DCP] Fix DCP customcarditem indentation in recipes_index.rst and fix link

beginner_source/hta_intro_tutorial.rst, beginner_source/hta_trace_diff_tutorial.rst
A follow up PR for #2723 with editorial changes.
=> An editorial pass on the HTA tutorials

conf.py
Since tensordict has moved to pytorch.org from pytorch-labs, updating the intersphinx mapping to reflect the change. This will fix the following build warning:
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://pytorch-labs.github.io/tensordict/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://pytorch-labs.github.io/tensordict/objects.inv
```
=> Update tensordict link in intersphinx mapping

beginner_source/dist_overview.rst, en-wordlist.txt
[PyTorch Distributed Overview](https://pytorch.org/tutorials/beginner/dist_overview.html) page
is widely used to learn basics of distributed package and its offerings. 
Seems like this page on [PyTorch Distributed Overview](https://pytorch.org/tutorials/beginner/dist_overview.html) was created before the  FSDP support was added in PyTorch. This PR adds missing FSDP reference.
- [ x] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [ x] Only one issue is addressed in this pull request
- [ x] No unnecessary issues are included into this pull request.
cc @wconstab @osalpekar @H-Huang @kwen2501
=> Add FSDP reference in PyTorch Distributed doc

advanced_source/coding_ddpg.py
By adding `pip install` cell as well as unhiding `from typing import Tuple`
=> Make coding_ddpg runnable in CoLab end to end

advanced_source/coding_ddpg.py
By setting spawn method to fork
Also, add missing parenthesis
cc @vmoens @nairbv
=> [BE] Make coding_ddpg.py runnable outside of Colab env

index.rst
Update the what's new section for the 2.2 release.
=> Update what's new for 2.2

.jenkins/build.sh
By making `FILES_TO_RUN` an environment variable
=> [CI] Fix selective downloads

intermediate_source/parametrizations.py
This makes it correct.
cc @albanD
=> Fix `CayleyMap`'s `right_inverse`, s/X/A

beginner_source/hyperparameter_tuning_tutorial.py, requirements.txt
To address numerous CVE that older Ray releases were affected by see https://www.anyscale.com/blog/update-on-ray-cves-cve-2023-6019-cve-2023-6020-cve-2023-6021-cve-2023-48022-cve-2023-48023
Use legacy APIs by setting `RAY_AIR_NEW_PERSISTENCE_MODE` environment variable to zero.
Please note, that this increases tutorial runtime from 4 to 10 min
=> Update ray to 2.7.2

beginner_source/hyperparameter_tuning_tutorial.py, requirements.txt
Reverts pytorch/tutorials#2789 somehow I've missed the red signal
=> Revert "Update ray to 2.7.2"

beginner_source/hyperparameter_tuning_tutorial.py, requirements.txt
To address numerous CVE that older Ray releases were affected by see https://www.anyscale.com/blog/update-on-ray-cves-cve-2023-6019-cve-2023-6020-cve-2023-6021-cve-2023-48022-cve-2023-48023
Use legacy APIs by setting RAY_AIR_NEW_PERSISTENCE_MODE environment variable to zero.
Move logic of adding fake properties to `sys.stdout` from `main` to top level imports, as `ray.tune` will expect `sys.stdout` to have an `encoding`, which is missing in sphinx
Please note, that this increases tutorial runtime from 4 to 10 min
=> (Re-land) Update ray to 2.7.2

recipes_source/distributed_device_mesh.rst
title
just fixes small typos in the device mesh tutorial
=> Fix typos in distributed_device_mesh.rst

advanced_source/super_resolution_with_onnxruntime.py
Because of this typo, the line was not properly rendered. 
Thank you. 
=> Typo fix in onnx tutorial

beginner_source/saving_loading_models.py
Hi thanks for the pytorch library! just a super small fix :)
=> Super tiny fix doc rendering

recipes_source/recipes/tuning_guide.py
Before this PR, the header shows literal backticks instead of fixed font.
> ``DistributedDataParallel``(find_unused_parameters=True)
=> Fix formatting

.jenkins/metadata.json, intermediate_source/torch_export_tutorial.py
Fixes https://github.com/pytorch/tutorials/issues/2805
* Changed functions passed to export to `nn.Module`
* Changed calling conventions of exported_program to `exported_program.module()`
* Removed mentions of equality constraints
* Added pointer to official [torch.export docs](https://pytorch.org/docs/main/export.html)
* Updated custom op meta implementations
* Added section on how to run exported program with inductor/tensorrt backends cc @chauhang
=> Update export tutorial

intermediate_source/char_rnn_classification_tutorial.py
The current RNN module does not implement the canonical "vanilla RNN" which consists of 3 linear layers, and a tanh operated on the sum of the projected x_t and h_{t-1}
The current implementation is confusing since it doesn't implement the canonical vanilla RNN. 
cc @albanD
=> Implements the canonical vanilla RNN rather than the current RNN

intermediate_source/torch_export_tutorial.py
Fixes build failure by moving aot inductor compilation part into just text, not interactive.
=> [export] Remove interactive aoti compilation

.ci/docker/requirements.txt, conf.py
We are not using it, so removing. 
It also, causes an issue with the tag selector on the landing page.
cc @brycebortree
=> Remove nbsphinx

.ci/docker/requirements.txt
pin torch version to most recent (2.3) to trigger docker rebuild
This way if we (or a pr author) wants to update the torch version they can just change the pin
=> Pin torch version to 2.3 and rebuild docker image

beginner_source/blitz/neural_networks_tutorial.py
`c1` outputs a Tensor with size (N, 6, 28, 28), and `s2` should not change the 6 into 16.
Fixes 2857
In the provided example in the comment section for the s2 layer, it is mentioned that s2 outputs a (N, 16, 14, 14) Tensor while its outputs a a (N, 6, 14, 14) Tensor. This is a minor typo, but may confuse the beginners.
cc @svekars @brycebortree @albanD
=> the output of s2 should not change the number of feature maps

recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
=> Update the hyperlink in torch_compile_user_defined_triton_kernel_tutorial.py

recipes_source/recipes/profiler_recipe.py
Fixes https://github.com/pytorch/pytorch/issues/73556
Remove suggestion to use Flamegraph in kineto tutorial
We no longer support Flamegraph so we must remove it
=> Remove all instances of Flamegraph

intermediate_source/TP_tutorial.rst
cross PR with https://github.com/pytorch/examples/pull/1259
cc @wconstab @osalpekar @H-Huang @kwen2501
=> [Tensor Parallel] update tutorial to simplify embedding + first transformer block

intermediate_source/_torch_export_nightly_tutorial.py
=> Fix up custom op tutorials

recipes_source/recipes/tuning_guide.py
Partly fixes https://github.com/pytorch/tutorials/issues/2861. Update the operator fusion section to use torch.compile instead of jit.script.
=> Update the fusion section of tuning_guide.py

intermediate_source/process_group_cpp_extension_tutorial.rst
=> [small] fix link

recipes_source/torch_compile_backend_ipex.rst
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @sekyondaMeta @svekars @kit1980 @brycebortree
=> update torch compile backend ipex with target device

.jenkins/validate_tutorials_built.py, intermediate_source/torchvision_tutorial.py
Fixes #2843 
`torch.utils.data` have platform specific behavior in multiprocessing see https://pytorch.org/docs/stable/data.html#platform-specific-behaviors
In order to run the tutorial as a script and as a notebook on all platforms, the number of workers was changed accordingly to the platform.
cc @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael @sekyondaMeta @svekars @kit1980 @brycebortree
=> Enable torchvision_tutorial

recipes_source/recipes/tuning_guide.py
Fixes #2861
cc @sekyondaMeta @svekars @kit1980 @brycebortree
=> Added CUDA graph, Tensor Core and Core pinning explaination

beginner_source/dist_overview.rst, en-wordlist.txt
Many overdue updates
* updating the overview to include TP/PP and DTensor/Devicemesh
* removing RPC, DataParallel as they are no longer supported
=> Clean up dist_overview.rst

beginner_source/dist_overview.rst
Didn't realize that this was a convention, so restoring it
=> Move edit note back to the top

.jenkins/validate_tutorials_built.py, advanced_source/cpp_custom_ops.rst, advanced_source/custom_ops_landing_page.rst, advanced_source/python_custom_ops.py, en-wordlist.txt, index.rst
I want to land this before PyTorch 2.4 (so we can link to these in PyTorch's nightly documentation) and then have a follow-up PR for 2.4 that actually runs the scripts (so that they can generate outputs).
https://github.com/pytorch/pytorch/issues/127443 to remind myself of the above.
NB: These two tutorials replace all of the existing custom ops (and cpp extensions) tutorials:
- advanced/cpp_extension
- advanced/torch_script_custom_ops
- advanced/torch_script_custom_classes
- advanced/dispatcher
In a follow-up PR we will add warnings to all of those tutorials stating that they are deprecated but we will preserve the text just in case people still need them (e.g. if they are not using PyTorch 2.4).
Test Plan:
- I tested these locally.
=> Add new Python and C++/CUDA Custom Op tutorials

beginner_source/introyt/tensors_deeper_tutorial.py
Fixes #2901 
in the pytorch dtype doc(link in below) is torch.bfloat16, but in tutorial istorch.bfloat , this might be mislead user to created dtype=torch.bfloat and get an error, might be better to make improvements: 
- Using doc link replace with static dtype explanation
tutorial link: https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html
doc link: https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype
**tutorial is ``torch.bfloat``**
**Got error when try to create**
**Should be ``dtype=torch.bfloat16``**
** Test Result: Local compile pages **
cc @albanD @sekyondaMeta @svekars @kit1980 @brycebortree
=> Replace dtype static list with a reference to data type doc

index.rst, intermediate_source/pipelining_tutorial.rst
PyTorch 2.4 release of `torch.distributed.pipelining`, pytorch docs: https://pytorch.org/docs/main/distributed.pipelining.html#pipeline-parallelism
https://fburl.com/workplace/9w8z3das
tutorial preview: https://docs-preview.pytorch.org/pytorch/tutorials/2962/intermediate/pipelining_tutorial.html
=> torch.distributed.pipelining tutorial

index.rst, intermediate_source/TCPStore_libuv_backend.rst, intermediate_source/pipelining_tutorial.rst
Update what's new for 2.4
Minor formatting fixes.
=> Update what's new for 2.4

.ci/docker/requirements.txt, .jenkins/build.sh
Merge when 2.4 becomes stable.
=> Update to switch back to use stable binaries

.ci/docker/requirements.txt, intermediate_source/pinmem_nonblock.py
@svekars sorry I missed the torchrl/tensordict dependency update in requirements.txt
=> Fix torchrl and tensordict requirements

recipes_source/distributed_checkpoint_recipe.rst
old:
new: https://docs-preview.pytorch.org/pytorch/tutorials/2990/recipes/distributed_checkpoint_recipe.html#formats
=> fix dcp tutorial formatting

recipes_source/recipes_index.rst, recipes_source/xeon_run_cpu.rst
To correct the link in index.rst for xeon_run_cpu.html. (previous PR #2931)
Hi @svekars I'm not quite sure about the principles which docs should be put into the 2nd-tier `recipes` subfolder. If this tutorial should be moved to the subfolder instead of changing the link in index.rst, please let me know so that I'll update this PR.
=> fix xeon_run_cpu.html link

intermediate_source/TP_tutorial.rst
This PR removes the non-existing code pointer, which caused confusion for readers e.g. https://github.com/pytorch/tutorials/issues/2956
replicated PR for #2998 to avoid ghstack
=> [Tensor Parallel] remove non-existing code pointer

recipes_source/recipes/profiler_recipe.py
this PR removes the `use_cuda` param as it originally shows below:
https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html#pytorch-profiler
Actually, the param `use_cuda` is deprecated
If this param is still in tutorials, it would mislead someone.  
cc @aaronenyeshi @chaekit @subramen
=> fix: rm `use_cuda` param

beginner_source/chatbot_tutorial.py
No issue number.
This PR fixes a minor capitalization error in the Chatbot tutorial and updates the link text.
=> Fixed capitalization error , updated link text in Chatbot tutorial

advanced_source/dynamic_quantization_tutorial.py, advanced_source/static_quantization_tutorial.rst, beginner_source/basics/quickstart_tutorial.py, beginner_source/basics/saveloadrun_tutorial.py, beginner_source/blitz/cifar10_tutorial.py, beginner_source/fgsm_tutorial.py, beginner_source/saving_loading_models.py, beginner_source/transfer_learning_tutorial.py, intermediate_source/autograd_saved_tensors_hooks_tutorial.py, intermediate_source/ddp_tutorial.rst, intermediate_source/tiatoolbox_tutorial.rst, prototype_source/fx_graph_mode_ptq_dynamic.py, prototype_source/fx_graph_mode_ptq_static.rst, prototype_source/pt2e_quant_ptq.rst, prototype_source/pt2e_quant_qat.rst, recipes_source/intel_neural_compressor_for_pytorch.rst, recipes_source/recipes/module_load_state_dict_tips.py, recipes_source/recipes/save_load_across_devices.py, recipes_source/recipes/saving_and_loading_a_general_checkpoint.py, recipes_source/recipes/saving_and_loading_models_for_inference.py, recipes_source/recipes/saving_multiple_models_in_one_file.py, recipes_source/recipes/warmstarting_model_using_parameters_from_a_different_model.py
Fixes #3007 
Fixing the issue and a bunch of other tutorials that use torch.load. In the generated output we have something like this:
We should fix all those warnings.
=> Add weights_only=True to torch.load

advanced_source/cpp_custom_ops.rst, advanced_source/python_custom_ops.py
Fixes https://github.com/pytorch/pytorch/issues/133318
We update the custom ops tutorials based on user feedback.
=> Improve custom ops tutorials

README.md
No issue number available. 
This PR removes an outdated step from the README file.
=> Removed outdated steps in README about running about setup.py

_static/css/custom.css
=> Fix hovering over the GCS search button

beginner_source/chatbot_tutorial.py, beginner_source/deeplabv3_on_android.rst, prototype_source/lite_interpreter.rst, recipes_source/mobile_interpreter.rst, recipes_source/mobile_perf.rst, recipes_source/ptmobile_recipes_summary.rst
Addresses https://www.internalfb.com/tasks/my_tasks?t=200046828
Preview links for changed files:
- https://docs-preview.pytorch.org/pytorch/tutorials/3016/beginner/deeplabv3_on_android.html
- https://docs-preview.pytorch.org/pytorch/tutorials/3016/recipes/mobile_perf.html
- https://docs-preview.pytorch.org/pytorch/tutorials/3016/recipes/ptmobile_recipes_summary.html
- https://docs-preview.pytorch.org/pytorch/tutorials/3016/prototype/lite_interpreter.html (Note: this file was renamed so this URL now redirects to https://docs-preview.pytorch.org/pytorch/tutorials/3016/recipes/mobile_interpreter.html, which is added in this PR.)
This PR adds warnings to select Pytorch mobile tutorials directing users to ExecuTorch.
=> Added warnings to select Pytorch mobile tutorials directing users to ExecuTorch 

.ci/docker/requirements.txt
This allows one to install pygame binaries for Python-3.11/3.12 runtime, while PyGame-2.1.2 was only available up to python-3.10, see https://pypi.org/project/pygame/2.1.2/#files
Fixes #3023
=> Fix #3023 - Upgrade pygame version to 2.6.0

prototype_source/gpu_quantization_torchao_tutorial.py
=> Fixed Rst formatting, minor text changes

conf.py, index.rst, recipes_source/torch_export_aoti_python.py
This is an experiment to see if helps with the SEO
- Adding a meta with description and keyword to the AOTInductor tutorial.
- Adding generic meta tags to all pages.
- Minor editorial fixes.
=> Add meta tag to torch_export_aoti_python

.gitmodules
Because we import the theme [here](https://github.com/pytorch/tutorials/blob/main/.ci/docker/requirements.txt#L47), we don't really need it as a submodule. It also seem to generate some unneeded [paths](https://docs-preview.pytorch.org/pytorch/tutorials/3035/sitemap.xml) in the sitemap.
=> Remove sphinx theme from .gitmodules

beginner_source/saving_loading_models.py
To load the model from disk, the `weights_only` parameter is for `torch.load` and not for `load_state_dict`. This pull request fixes the error.
=> fix typo in loading model from disk code

beginner_source/saving_loading_models.py
Fixes #3041 
1. "weights_only" is augument of torch.load, not for model.load_state_dict
Here is the doc:
https://pytorch.org/docs/stable/generated/torch.load.html
=> Fix 2 incorrect argument positioning in Tutorial

prototype_source/README.txt, prototype_source/flight_recorder_tutorial.rst, prototype_source/prototype_index.rst
Summary:
Recreating pull request #3024 because of bad merges. 
Re-add flight recorder tutorial with prior comments addressed
Test Plan:
Ran:
`rst2html5 flight_recorder_tutorial.rst flight_recorder_tutorial.html
`
Also, preview documentation is here: https://docs-preview.pytorch.org/pytorch/tutorials/3040/prototype/flight_recorder_tutorial.html
Reviewers: fduwjj, svekars
- [x ] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [x ] Only one issue is addressed in this pull request
- [x ] Labels from the issue that this PR is fixing are added to this pull request
- [x ] No unnecessary issues are included into this pull request.
=> [c10d][Doc] Add a flight recorder tutorial

.ci/docker/requirements.txt, .gitmodules, conf.py
To improve pages discoverability adding sitemap to the tutorials site.
Adding sitemap generation using [sphinx-sitemap](https://pypi.org/project/sphinx-sitemap/).
=> Add sitemap

advanced_source/extend_dispatcher.rst
Fixes #2991
Fixes the issue and some typos
cc @svekars @brycebortree @sekyondaMeta
=> Fixes #2991

prototype_source/flight_recorder_tutorial.rst
This is the PR trying to update the tutorial of FR to reflect the latest changes and provide more context on how to use it.
=> Update FR tutorial to include file path, writer and print usage

prototype_source/flight_recorder_tutorial.rst
Summary:
1. Move FILE option to "Optional settings" section.
2. Add a link to how customer can add a DebugInfoWriter.
3. Clarify a sentence.
Test Plan:
Test manually.
Reviewers:
=> Minor fixes

.github/workflows/StalePRs.yml
Creating a github action to close stale PRs. 
Marks PRs with no activity for 60 days as stale. Closes any PRs with `stale` lable and no activity after 30 days.
Script copied from the PyTorch repo action with minor modifications.
**Need to add a `no-stale` label to the repo for PRs that have been idle for longer than 60 days but should not be marked as `stale`.**
=> GIthubAction to close stale PRs 

prototype_source/inductor_windows_cpu.rst
Follow up on https://github.com/pytorch/tutorials/pull/3062/files#r1784933084
cc @brycebortree @sekyondaMeta
=> Fix a typo in the inductor Windows CPU tutorial

prototype_source/flight_recorder_tutorial.rst
Update the tutorial to reflect a feature we have added previously. We didn't test it previously. Now with the feature for the arg ready, we want to update the tutorial to reflect that.
=> [FR][Tutorial] Update the tutorial to reflect the pg command arg

prototype_source/flight_recorder_tutorial.rst
Summary:
Don't interrupt user's flow that they may need to install `tabulate`. Also, show them the actual command that they need to run to install `tabulate`.
This was feedback from @lessw2020.
Test Plan:
Look at rendered doc.
=> [FR][tutorial] Minor fix

intermediate_source/scaled_dot_product_attention_tutorial.py
=> Fix formatting in the scaled_dot tutorial

intermediate_source/torchrec_intro_tutorial.py
fixes headings on sidebar in torchrec tutorial
=> [torchrec tutorial] fix headings

beginner_source/introyt/modelsyt_tutorial.py
Transformer tutorial is deprecated so removing this link.
cc @svekars @brycebortree @sekyondaMeta
=> Update modelsyt_tutorial.py to remove deprecated link

beginner_source/basics/saveloadrun_tutorial.py
Update https://pytorch.org/tutorials/beginner/basics/saveloadrun_tutorial to fix a broken link and some formatting.
cc @svekars @brycebortree @sekyondaMeta
=> Update saveloadrun_tutorial.py to fix a broken link

recipes_source/regional_compilation.py
Some linter also made changes to this file.
=> Add assert to regional compilation tutorial

intermediate_source/torchrec_tutorial.rst
Add a redirect to the new torchrect tutorial
=> Redirect from the old torchrec tutorial to the new one

prototype_source/inductor_windows_cpu.rst
Fixes #3086 
update link to a intel compiler guide with performance data
cc @svekars @brycebortree @sekyondaMeta
=> update link to a intel compiler guide with performance data

recipes_source/distributed_checkpoint_recipe.rst
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #3124
Command in the tutorial is outdated, see https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/format_utils.py
=> Fix DCP tutorial command

intermediate_source/ddp_tutorial.rst
Summary:
1. Add "set_device" call to keep things consistent between all DDP tutorials.
This was inspired by the following change in the PyTorch repo: https://github.com/pytorch/examples/pull/1285#pullrequestreview-2304060807
2. Update documentation to be more clearer.
Test Plan:
Ran tutorial with the applied changes and we see:
```
Running basic DDP example on rank 3.
Running basic DDP example on rank 1.
Running basic DDP example on rank 2.
Running basic DDP example on rank 0.
Finished running basic DDP example on rank 0.
Finished running basic DDP example on rank 1.
Finished running basic DDP example on rank 3.
Finished running basic DDP example on rank 2.
Running DDP checkpoint example on rank 2.
Running DDP checkpoint example on rank 1.
Running DDP checkpoint example on rank 0.
Running …
```
=> [doc] Fix to DDP tutorial

beginner_source/ptcheat.rst
Updates the pt cheat page to
- no longer mention jit/torchscript
- mention zero_grad for optim
- update the list of optims
=> Update PT Cheat page to stop referencing torchscript

intermediate_source/process_group_cpp_extension_tutorial.rst
Removing mention of the Fully_Shared_Data_Parallel as it is a dead link=
=> Fixed links in process_group_cpp_extension_tutorial.rst

recipes_source/torch_compile_caching_tutorial.rst
Add descriptions of new configuration settings exposed by AOTAutogradCache (https://github.com/pytorch/pytorch/pull/141981). 
cc @williamwen42 @msaroufim @anijain2305
=> Add AOTAutogradCache to caching tutorials

recipes_source/torch_compile_caching_tutorial.rst
Follow up on https://github.com/pytorch/tutorials/pull/3177
cc @brycebortree @sekyondaMeta @AlannaBurke
=> Fix typo in torch_compile_caching_tutorial.rst

intermediate_source/dist_tuto.rst
Fixes an invalid line wrapping leading to:
=> fix line wrapping

advanced_source/cpp_frontend.rst
The issue in example repo has been fixed but on website it did not update. I found it today while following the [tutorials](https://pytorch.org/tutorials/advanced/cpp_frontend.html).
Issue see [here](https://github.com/pytorch/examples/issues/819#issue-686390601), main code repo PR: [here](https://github.com/pytorch/examples/pull/1207#issue-2061218185). 
This PR adopted the solution mentioned in the issue and tested with the latest version libtorch(current 2.5.1) with cuda 12.6.
cc @albanD @jbschlosser
=> Fix the DCGAN C++ shape warning

prototype_source/flight_recorder_tutorial.rst
Summary:
The small example code isn't rendering on the page. 
Remove caption string as this seems to be the problem.
Test Plan:
Tested locally and on sandbox.
Without the fix: note missing code after "Note".
Broken screenshot:
Broken link here:
https://pytorch.org/tutorials/prototype/flight_recorder_tutorial.html#an-end-to-end-example
After the fix:
Fixed screenshot:
Sandbox link here: 
https://docs-preview.pytorch.org/pytorch/tutorials/3189/prototype/flight_recorder_tutorial.html#an-end-to-end-example
=> [doc] fix flight recorder tutorial

beginner_source/blitz/cifar10_tutorial.py
Fixes #3192 
Removes `.data` when getting predictions in the [CIFAR10 tutorial](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#test-the-network-on-the-test-data).
cc @albanD @jbschlosser
=> Remove Tensor.data attribute from tutorial

.jenkins/validate_tutorials_built.py, advanced_source/coding_ddpg.py, advanced_source/pendulum.py, intermediate_source/dqn_with_rnn_tutorial.py, intermediate_source/reinforcement_ppo.py
Fixes #3195 
Fixing TorchRL scripts for Pytorch 2.6 release
=> Fix torchrl scripts for PT 2.6 / TorchRL>=0.6

advanced_source/cpp_custom_ops.rst, index.rst
In 2.6, we can confidently tell people to use the py_limited_api to build python agnostic wheels.
Including the instructions within the existing custom op tutorial.
=> Mention Python agnosticism in custom ops tutorial

advanced_source/python_custom_ops.py, index.rst
Before:
This confused me everytime cuz PyTorch and Python were too similar, so changing "Python Custom Operators" to "Custom Python Operators" to be super obvious. This is step 0 in updating this section of the tutorials in general, as several pieces of this sidebar are outdated. The plan for the bigger update is in a few weeks when Core does BE week.
After:
=> Clarify the Extending PyTorch sidebar by making differences more obvious

advanced_source/custom_ops_landing_page.rst, advanced_source/python_custom_ops.py
See https://github.com/pytorch/pytorch/issues/143786
=> Clarify Python custom operators do not work without Python

intermediate_source/inductor_debug_cpu.py
Links in the tutorial [Inductor CPU backend debugging and profiling
](https://pytorch.org/tutorials/intermediate/inductor_debug_cpu.html) is invalid, and leading to 404 pages.
Change `troubleshooting` and `GPU performance profiling` to valid url address
**Test Result**
**Before**
**After**
cc @svekars @brycebortree @sekyondaMeta @AlannaBurke @jgong5
=> Fix invalid page links in tutorial

intermediate_source/inductor_debug_cpu.py
Original link (https://pytorch.org/docs/stable/dynamo/troubleshooting.html) is dead, use (https://pytorch.org/docs/stable/torch.compiler_troubleshooting.html) instead.
cc @svekars @brycebortree @sekyondaMeta @AlannaBurke
=> Fix dead link for compiler troubleshooting

advanced_source/pendulum.py
Intended available links
cc @svekars @brycebortree @sekyondaMeta @AlannaBurke
=> fix reference path links

recipes_source/torch_compiler_set_stance_tutorial.py
Title
cc @msaroufim @anijain2305
=> add torch.compiler.set_stance tutorial

intermediate_source/rpc_tutorial.rst
Fixing broken links in RPC Tutorial
=> Fix a broken link in rpc_tutorial.rst

beginner_source/pytorch_with_examples.rst
Fix link in pytorch-with-examples
=> Fix a broken link in pytorch_with_examples.rst

advanced_source/cpp_frontend.rst
Update broken links
cc @svekars @AlannaBurke
=> Fix broken links in cpp_frontend.rst

recipes_source/torch_compile_user_defined_triton_kernel_tutorial.py
The new API is a more advanced complement to the existing APIs.
cc @williamwen42 @msaroufim @anijain2305
=> Update user-defined triton kernels tutorial with new torch.library.triton_op

.jenkins/validate_tutorials_built.py, intermediate_source/transformer_building_blocks.py
https://github.com/pytorch/tutorials/issues/3161. Also fix https://github.com/pytorch/tutorials/issues/3176
=> Validate transformer tutorial builds against 2.6

intermediate_source/pinmem_nonblock.py
Adds some more info on when it is unsafe to use `non_blocking` (namely with pinned tensors)
cc @nairbv
=> Add pageable/pinned tensor to cuda reliability note in pinmem tutorial

intermediate_source/dist_tuto.rst
cc @wconstab @osalpekar @H-Huang @kwen2501
=> Fix typo `size` to `world_size`

recipes_source/distributed_device_mesh.rst
Fixing typo 'sequance -> sequence'
The fix is minimal and won't break anything
=> fixing typo "sequance->sequence"

recipes_source/torch_compile_caching_tutorial.rst
Fix the source code for saving
=> Fix caching tutorial order

index.rst
Follow the suggestion from https://github.com/pytorch/tutorials/pull/3223#discussion_r1973923247
This PR adds the new custom card for ONNX new tutorial page, and fix the 404 Error on registry page.
=> [ONNX] Add and fix custom cards for ONNX

.github/workflows/link_checkPR.yml
The tags in tj-actions/changed-files action are compromised and are leaking GitHub secrets in repos using the compromised repo. This pins the action to a known good hash.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
=> Tags in tj-actions/changed-files are compromised

advanced_source/python_custom_ops.py
We tightned invariants in PyTorch 2.7 that exposed a bug with the python custom ops tutorial. This PR fixes said bug.
Fixes https://github.com/pytorch/pytorch/issues/149425
Test Plan:
- tested locally
=> Fix python custom ops tutorial

advanced_source/cpp_extension.rst
Fixes #2342
This is a minor update to the C++ Extension with a note about AMD GPU support.
=> [ROCm] Update C++ Extension Tutorial for AMD GPU

.ci/docker/requirements.txt
Fixes https://github.com/pytorch/tutorials/issues/3297
Update onnxscript to >= 0.2.2 to ensure the docker image contains the latest version
=> Update onnxscript in requirements

.ci/docker/requirements.txt, .jenkins/validate_tutorials_built.py, advanced_source/coding_ddpg.py, advanced_source/semi_structured_sparse.py, intermediate_source/reinforcement_ppo.py
=> Bump torchrl and tensordict to 0.7.2

intermediate_source/torch_export_tutorial.py, recipes_source/torch_export_aoti_python.py
The compiled model run takes the same input as Eager. No need to explicitly compose args as a tuple.
=> Fix the AOTI example

_templates/layout.html
=> Fix minor issue in layout.html

.github/workflows/build-tutorials.yml
Why we're making this change
-------------------------------
PR authors are frustrated with `torch.compile` tutorials, which aren't supported on our older workers. As more tutorials adopt `torch.compile`, users must constantly update `metadata.json` to ensure their tutorials run on compatible workers.
This PR moves these tutorials to G5 instances, providing a consistent environment that supports `torch.compile` out of the box, eliminating the need for manual configuration and improving the overall developer experience. This change should also help to make the whole tutorial build faster.
Cons: Less and less tutorials are actually runnable on Colab, which still serves only T4 machines in their free tier
=> Run tutorials on g5

.jenkins/validate_tutorials_built.py
Temporarily disabling recipes_source/recipes/reasoning_about_shapes.py
cc: @mikaylagawarecki
=> Disable reasoning_about_shapes.py

index.rst
Updating the what's new section with 2.7 tutorials.
=> Updating tutorials for 2.7.

prototype_source/inductor_windows.rst
=> fix index format issue

beginner_source/basics/optimization_tutorial.py
=> fix a typo in optimization_tutorial.py

.jenkins/validate_tutorials_built.py, conf.py
Replace sphinx gallery's generate_file_rst call with a wrapper that calls that function but in a subprocess, and remove some things that we added in order to handle files changing global state
I tried using multiprocess.pool and apply async but ran into pickling problems.  I don't understand why this current implementation doesn't have that issue
parallelism got added in some version of sphinx gallery, but it uses joblib, which seems to result in errors (conflicts with functions in subprocess library?  im not sure).  Additionally, it has no effect if you set parallel = 1 (it will not put each file run into its own process and run singly) so you need parallel >= 2, but I'm not sure if there are any tutorials that require being run on their own (ex for memory profiling)
Afaict (although I …
=> [build] Monkeypatch gen_rst to call inside subprocess

beginner_source/examples_autograd/polynomial_autograd.py, beginner_source/examples_autograd/polynomial_custom_function.py
header "# -*- coding: utf-8 -*-" is only needed for Python 2.x.
Since Python 3.x default encoding is utf-8 and is header is not necessary. It gets displayed in the tutorials here: https://docs.pytorch.org/tutorials/beginner/pytorch_with_examples.html
and could confuse newcomers who might think that encoding header is necessary
=> remove obsolete encoding headers

prototype_source/nestedtensor.py
=> Fix link format

beginner_source/basics/data_tutorial.py
Replacing obsolete function read_image with its up-to-date equivalent decode_image in data tutorials
Fixes #3370
Replaces obsolete function in the data loaders documentation.
cc @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael
=> Update obsolete function "read_image" to "decode_image"

advanced_source/dynamic_quantization_tutorial.py
Fixes #3254
- Added wget command to download word_language_model_quantize.pth
- Included note about file placement  
- Improved tutorial usability by providing missing download information
- Referenced official Makefile download method
This PR addresses issue #3254 by adding clear download instructions for the pretrained model file `word_language_model_quantize.pth` required by the dynamic quantization tutorial. The tutorial previously assumed users already had the model file without explaining where to download it.
The fix adds a clear note with a wget command using the same trusted URL found in the repository's Makefile (lines 65-66: https://github.com/pytorch/tutorials/blob/main/Makefile#L65), along with guidance on file placement. This ensures users get the same reliable download …
=> Add download instructions for pretrained model in dynamic quantization tutorial

beginner_source/examples_autograd/polynomial_custom_function.py
Fixes #2797
- This PR corrects the misleading explanation of `ctx.save_for_backward` in the `two_layer_net_custom_function.py` tutorial. The original text incorrectly stated that arbitrary objects can be cached using `ctx.save_for_backward`, whereas only tensors are supported.
- The updated docstring now accurately reflects PyTorch’s autograd API.
cc @albanD @jbschlosser
=> docs: Fix incorrect usage description of ctx.save_for_backward

intermediate_source/ddp_tutorial.rst
Fixes #3288
Added `import os` to the documentation since it was missing
cc @wconstab @osalpekar @H-Huang @kwen2501
=> Add import os to example code block

README.md
=> Update CONTRIBUTING.md 

recipes_source/recipes/profiler_recipe.py
This PR is a minor fix for some table formatting issues in the profiler_recipe file. Specifically, the CUDA and XPU tables after the first GPU profiling section were not being rendered similar to the other tables.
I also recognized that the current method of specifying `activities = [ProfilerActivity.CPU, ProfilerActivity.CUDA, ProfilerActivity.XPU]` does not cause XPU profiling to be captured, but this seems more like an issue in Pytorch than in the tutorial, so I will file an issue in Pytorch to fix this.
cc @svekars @sekyondaMeta @AlannaBurke @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233
=> Fix XPU and CUDA tables in profiler recipe.

recipes_source/recipes/profiler_recipe.py
=> remove unnecessary term XPUs from profiler

beginner_source/hyperparameter_tuning_tutorial.py
fix broken URL:
https://docs.ray.io/en/master/ray-core/using-ray-with-gpus.html#fractional-gpus ->
https://docs.ray.io/en/latest/ray-core/scheduling/accelerators.html#fractional-accelerators
based on the archived copy of the original link here: https://web.archive.org/web/20220313114338/https://docs.ray.io/en/master/ray-core/using-ray-with-gpus.html#fractional-gpus
it looks like the new link is referring to the same content
=> fix broken URL

recipes_source/torch_compile_caching_tutorial.rst
It was mentioned but never explained
=> Add explaination of AutotuneCache to torch compile cache tutorial

recipes_source/recipes/profiler_recipe.py
=> Profiler Recipe Update

intermediate_source/TP_tutorial.rst
Fixes Pytorch Tutorial Audit - Tensor Parallelism Tutorial
Migrate from FSDP1 to FSDP2 in Tensor Parallelism tutorial
Related changes in examples repo: https://github.com/pytorch/examples/pull/1372
=> Migrate fsdp1 -> fsdp2 in Tensor Parallelism Tutorial

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/scripts/docathon-label-sync.py, .github/workflows/MonthlyLinkCheck.yml, .github/workflows/StalePRs.yml, .github/workflows/link_checkPR.yml, .github/workflows/spelling.yml, .jenkins/build.sh, .jenkins/post_process_notebooks.py, .lintrunner.toml, .lycheeignore, CONTRIBUTING.md, docathon-leaderboard.md, redirects.py, tutorial_submission_policy.md
Removes the files from the exclusion lists and run `lintrunner --all-files -a` to apply the changes
This is only files at the root level and in `.github` and `.jenkins` folders
The linters should just be whitespace changes
=> [ez][BE] Apply lintrunner to non tutorials files

intermediate_source/TP_tutorial.rst
Fixes #ISSUE_NUMBER. This PR is to make the TP tutorial up-to-date with DTensor changes.
After DTensor enhancement, we are not able to use DTensor to handle the change of `num_heads` instead of manually handle the tensor shape while TP is applied.
Corresponding changes in `pytorch/examples`: https://github.com/pytorch/examples/pull/1373
=> Using DTensor to handle local num_heads change while TP is applied

recipes_source/distributed_device_mesh.rst
Since we are deprecating FSDP1 we need to update the place where FSDP1 is used to use FSDP2 in the tutorial of DeviceMesh.
=> Update tutorial of device mesh to use fsdp2

beginner_source/dist_overview.rst, intermediate_source/FSDP1_tutorial.rst
resolves pytorch doc audit. use fsdp2 and remove fsdp1 in distributed overview
=> [distributed] point to fsdp2 and remove fsdp1 in distributed overview

distributed.rst
resolve pytorch audit - remove fsdp1 from distributed homepage as fsdp1 is deprecated
=> remove fsdp1 from distributed homepage

index.rst, intermediate_source/FSDP_tutorial.rst
reslovle pytorch doc audit. remove fsdp1 advanced tutorial from index
=> remove fsdp1 advanced tutorial from index

.ci/docker/requirements.txt
@svekars I think we should upgrade torchrl and tensordict - 0.7 is quite old for both!
=> Upgrade torchrl and tensordict requirements

recipes_source/intel_extension_for_pytorch.rst
Fixes #3421 
Removing the deprecated torchscript related example codes, as well as some other code updates.
=> updates for ipex example page

unstable_source/flight_recorder_tutorial.rst
Fix this warning
`Warning: Environment variable TORCH_NCCL_DEBUG_INFO_TEMP_FILE is deprecated; use TORCH_FR_DUMP_TEMP_FILE instead (function operator())`
=> fix deprecated env var

intermediate_source/FSDP_tutorial.rst
This small PR fixes the `FSDPModule` reference by removing a weird hidden zero-width space (`U+200B`). Steps to reproduce:
1. Visit the [FSDP tutorial](https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html).
2. Click on the `FSDPModule` reference. 
3. It will redirect you to: 
```
https://docs.pytorch.org/tutorials/intermediate/%E2%80%8Bhttps://docs.pytorch.org/docs/main/distributed.fsdp.fully_shard.html#torch.distributed.fsdp.FSDPModule
```
=> Fix FSDPModule reference

intermediate_source/reinforcement_ppo.py
=> Fix broken links in reinforcement.ppo doc

recipes_source/distributed_async_checkpoint_recipe.rst
set checkpoint_future properly in pinned mem tutorial
=> Fix async cp recipe

intermediate_source/realtime_rpi.rst
This updates the raspberry pi tutorial with the latest `picamera2` and Raspberry Pi 5.
Test plan:
manually ran instructions + code
CI
=> realtime_rpi: updated for raspberry pi 5
